### ISSUE TITLE
Database is locked Error

### ISSUE THREAD

**Issue by HenrikSolver** [matrix-org/dendrite#1252]
Running dendrite-monolith-server with sqlite built from source (git pulled 20200807).
After joining a few rooms (#dendrite and #dendrite-dev) from element-web and also logging in to the same account with element-android, a lot of "database is locked" errors show up in the log. Can be seen in attached log.

[Monolith1.log.gz](https://github.com/matrix-org/dendrite/files/5045247/Monolith1.log.gz)

**Comment by HenrikSolver** [comment]
Got this today.
INFO[2020-08-09T12:47:22.867651102Z] [github.com/matrix-org/dendrite@/eduserver/input/input.go:104] sendTypingEvent
         Producing to topic 'typingServerOutput'       room_id="!OGEhHVWSdvArJzumhm:matrix.org" typing=false user_id="@jcc:matrix.debian.social"
panic: the ContinualConsumer failed to SetPartitionOffset: database is locked

goroutine 121 [running]:
github.com/matrix-org/dendrite/internal.(*ContinualConsumer).consumePartition(0xc000336180, 0x120fe00, 0xc00033af00)
        github.com/matrix-org/dendrite@/internal/consumers.go:114 +0x29d
created by github.com/matrix-org/dendrite/internal.(*ContinualConsumer).StartOffsets
        github.com/matrix-org/dendrite@/internal/consumers.go:101 +0x4f4
