### ISSUE TITLE
CS peek sytest flakes about 10% of the time with db deadlock in sqlite

### ISSUE THREAD

**Issue by ara4n** [matrix-org/dendrite#1409]
Sytest is from https://github.com/matrix-org/sytest/pull/944/files (in this instance, it's the test to check that peeking by alias works, but it can happen to any of them)

It looks like this when it jams:

```
[server]: time="2020-09-07T22:43:25.649467000Z" level=info msg="Sent event to roomserver" func="SendEvent\n\t" file=" [github.com/matrix-org/dendrite@/clientapi/routing/sendevent.go:108]" event_id="$HctHckxg92w8Kouy4abmX1OGXuSyxGxyvTpvsrv8kf0" req.id=myw1xGEtMaf4 req.method=PUT req.path="/_matrix/client/r0/rooms/!rHrmkzrfrnSrVMYS:localhost:8800/send/m.room.message/2" room_id="!rHrmkzrfrnSrVMYS:localhost:8800" room_version=5 user_id="@anon-20200907_224324-9:localhost:8800"
[server]: time="2020-09-07T22:43:25.649561000Z" level=trace msg="Responding (59 bytes)" func="respond\n\t" file=" [github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:173]" code=200 req.id=myw1xGEtMaf4 req.method=PUT req.path="/_matrix/client/r0/rooms/!rHrmkzrfrnSrVMYS:localhost:8800/send/m.room.message/2"
[server]: time="2020-09-07T22:43:25.650986000Z" level=trace msg="Incoming request" func="RequestWithLogging\n\t" file=" [github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:123]" req.id=kZzE1VI6ry7s req.method=GET req.path=/_matrix/client/r0/sync
[server]: time="2020-09-07T22:43:25.651898000Z" level=debug msg="QueryKeyChanges request p=0,off=26,to=-1 response p=0 off=0 uids=[]" func="DeviceListCatchup\n\t" file=" [github.com/matrix-org/dendrite@/syncapi/internal/keychange.go:103]" context=missing
[server]: time="2020-09-07T22:43:25.651961000Z" level=info msg=Responding func="OnIncomingSyncRequest\n\t" file=" [github.com/matrix-org/dendrite@/syncapi/sync/requestpool.go:140]" device_id=yhfw5OUI limit=20 next=s97_0.dl-0-0 req.id=kZzE1VI6ry7s req.method=GET req.path=/_matrix/client/r0/sync since=s96_0.dl-0-26 timed_out=false timeout=1s user_id="@anon-20200907_224324-9:localhost:8800"
[server]: time="2020-09-07T22:43:25.652003000Z" level=trace msg="Responding (804 bytes)" func="respond\n\t" file=" [github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:173]" code=200 req.id=kZzE1VI6ry7s req.method=GET req.path=/_matrix/client/r0/sync
[server]: time="2020-09-07T22:43:25.653582000Z" level=trace msg="Incoming request" func="RequestWithLogging\n\t" file=" [github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:123]" req.id=m0r6ydUASlKl req.method=POST req.path="/_matrix/client/r0/peek/#peektest-20200907_224324:localhost:8800"
[server]: time="2020-09-07T22:43:25.654129000Z" level=info msg="Producing to topic 'DendriteOutputRoomEvent'" func="WriteOutputEvents\n\t" file=" [github.com/matrix-org/dendrite@/roomserver/internal/input/input.go:98]" room_id="!rHrmkzrfrnSrVMYS:localhost:8800" type=new_peek
[server]: time="2020-09-07T22:43:25.654621000Z" level=trace msg="Responding (46 bytes)" func="respond\n\t" file=" [github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:173]" code=200 req.id=m0r6ydUASlKl req.method=POST req.path="/_matrix/client/r0/peek/#peektest-20200907_224324:localhost:8800"
[server]: time="2020-09-07T22:43:25.654624000Z" level=debug msg="roomserver output log: ignoring unknown output type" func="onMessage\n\t" file=" [github.com/matrix-org/dendrite@/currentstateserver/consumers/roomserver.go:68]" type=new_peek
[server]: time="2020-09-07T22:43:25.654628000Z" level=debug msg="roomserver output log: ignoring unknown output type" func="onMessage\n\t" file=" [github.com/matrix-org/dendrite@/federationsender/consumers/roomserver.go:101]" type=new_peek
[server]: time="2020-09-07T22:43:25.654633000Z" level=debug msg="roomserver output log: ignoring unknown output type" func="onMessage\n\t" file=" [github.com/matrix-org/dendrite@/appservice/consumers/roomserver.go:85]" type=new_peek
[server]: time="2020-09-07T22:43:25.655983000Z" level=trace msg="Incoming request" func="RequestWithLogging\n\t" file=" [github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:123]" req.id=0lh8OYBFOoDe req.method=GET req.path=/_matrix/client/r0/sync
[server]: panic: the ContinualConsumer in "syncapi/roomserver" failed to SetPartitionOffset: database is locked
[server]: 
[server]: goroutine 160 [running]:
[server]: github.com/matrix-org/dendrite/internal.(*ContinualConsumer).consumePartition(0xc0001e4550, 0x4f027a0, 0xc0003f26e0)
[server]: 	github.com/matrix-org/dendrite@/internal/consumers.go:115 +0x2fc
[server]: created by github.com/matrix-org/dendrite/internal.(*ContinualConsumer).StartOffsets
```

**Comment by ara4n** [comment]
I wonder if this may be related to MarkPeeksAsOld() trying to write to the db in a read-only txn block in `getStateDeltas()`. in postgres this crashes outright.

**Comment by S7evinK** [comment]
Closing this, as `SetPartitionOffset` doesn't exist anymore and the code changed throughout the years to fix locked database issues. (Also, the test doesn't seem to flake anymore)
