### ISSUE TITLE
[v0.3.0] Test Fail on armv7

### ISSUE THREAD

**Issue by 6543** [matrix-org/dendrite#1585]
### Background information

- **Dendrite version or git SHA**:  v0.3.0
- **Monolith or Polylith?**:  Monolith
- **SQLite3 or Postgres?**:  -
- **Running in Docker?**:  no
- **`go version`**: 1.15.4

### Description

while updating the alpine package ... the CI hit an issue:
https://gitlab.alpinelinux.org/6543/aports/-/jobs/248970

### Trace

```
time="2020-11-16T22:51:18.032040788Z" level=info msg="Dendrite version 0.3.0" func="NewBaseDendrite\n\t" file=" [/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/internal/setup/base.go:102]"
time="2020-11-16T22:51:48.375302543Z" level=warning msg="Error sending request to https://localhost:36351/_matrix/federation/v2/invite/%21roomid:localhost/$mGiPO3oGjQfCkIUw:localhost: context deadline exceeded" func="RoundTrip\n\t" file=" [/home/buildozer/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20201020162226-22169fe9cda7/client.go:146]" context=missing out.req.ID=Dqz9apfJPgKC out.req.method=PUT out.req.uri="matrix://localhost:36351/_matrix/federation/v2/invite/%21roomid:localhost/$mGiPO3oGjQfCkIUw:localhost"
time="2020-11-16T22:51:48.375568945Z" level=warning msg="Outgoing request failed" func="DoHTTPRequest\n\t" file=" [/home/buildozer/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20201020162226-22169fe9cda7/client.go:417]" context=missing error="Put \"matrix://localhost:36351/_matrix/federation/v2/invite/%21roomid:localhost/$mGiPO3oGjQfCkIUw:localhost\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" out.req.ID=Dqz9apfJPgKC out.req.method=PUT out.req.uri="matrix://localhost:36351/_matrix/federation/v2/invite/%21roomid:localhost/$mGiPO3oGjQfCkIUw:localhost"
time="2020-11-16T22:52:04.425675902Z" level=error msg="Request panicked!\ngoroutine 147 [running]:\nruntime/debug.Stack(0x2e002c0, 0x32f57fc, 0x2e00300)\n\t/usr/lib/go/src/runtime/debug/stack.go:24 +0x80\ngithub.com/matrix-org/util.Protect.func1.1(0x2d3e500, 0x153aad8, 0x2d5e280)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:98 +0xfc\npanic(0x149ce20, 0x1868838)\n\t/usr/lib/go/src/runtime/panic.go:969 +0x168\ngithub.com/matrix-org/dendrite/roomserver/api.IsServerBannedFromRoom(0x153b9f8, 0x2eea760, 0x0, 0x0, 0x314c0e0, 0x11, 0x2d5a0b1, 0xf, 0xce7ae8)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/roomserver/api/wrapper.go:165 +0x90\ngithub.com/matrix-org/dendrite/federationapi/routing.Setup.func5(0x2d3e780, 0x2f94210, 0x2eeaa20, 0x0, 0x2eea760, 0x2d5a0b1, 0xf)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/federationapi/routing/routing.go:123 +0xdc\ngithub.com/matrix-org/dendrite/internal/httputil.MakeFedAPI.func1(0x2d3e780, 0x0, 0x0, 0x0, 0x0)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/internal/httputil/httpapi.go:204 +0x1a4\ngithub.com/matrix-org/util.(*jsonRequestHandlerWrapper).OnIncomingRequest(0x2c10dd8, 0x2d3e780, 0x0, 0xbec100, 0xe7a230f8, 0x44)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:79 +0x28\ngithub.com/matrix-org/util.MakeJSONAPI.func1(0x153aad8, 0x2d5e280, 0x2d3e780)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:141 +0x5c\ngithub.com/matrix-org/util.Protect.func1(0x153aad8, 0x2d5e280, 0x2d3e500)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:103 +0x68\nnet/http.HandlerFunc.ServeHTTP(...)\n\t/usr/lib/go/src/net/http/server.go:2042\ngithub.com/matrix-org/dendrite/internal/httputil.MakeExternalAPI.func1(0x153aad8, 0x2d5e280, 0x2d3e400)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/internal/httputil/httpapi.go:123 +0x1b0\nnet/http.HandlerFunc.ServeHTTP(0x2eb4ee0, 0x153aad8, 0x2d5e280, 0x2d3e400)\n\t/usr/lib/go/src/net/http/server.go:2042 +0x34\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0x2ce1b00, 0x153aad8, 0x2d5e280, 0x2d3e200)\n\t/home/buildozer/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x9c\nnet/http.serverHandler.ServeHTTP(0x2cc8510, 0x153aad8, 0x2d5e280, 0x2d3e200)\n\t/usr/lib/go/src/net/http/server.go:2843 +0x90\nnet/http.(*conn).serve(0x2eee1e0, 0x153b998, 0x2eea140)\n\t/usr/lib/go/src/net/http/server.go:1925 +0x834\ncreated by net/http.(*Server).Serve\n\t/usr/lib/go/src/net/http/server.go:2969 +0x314\n" func="1\n\t" file=" [/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:97]" context=missing panic="runtime error: invalid memory address or nil pointer dereference"
time="2020-11-16T22:52:04.427973119Z" level=warning msg="incoming federation request failed to notify server alive" func="Wakeup\n\t" file=" [/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/internal/httputil/httpapi.go:229]" error="Post \"http://localhost:7775/api/federationsender/performServersAlive\": dial tcp [::1]:7775: connect: connection refused" origin="localhost:36351" req.id=a5oP6slGjUUg req.method=PUT req.path="/_matrix/federation/v2/invite/!roomid:localhost/$0SFh2WJbjBs3OT+E0yl95giDKo/3Zp52HsHUUk4uPyg"
time="2020-11-16T22:52:04.428019099Z" level=error msg="Request panicked!\ngoroutine 147 [running]:\nruntime/debug.Stack(0x2e00440, 0x32f57fc, 0x2e00480)\n\t/usr/lib/go/src/runtime/debug/stack.go:24 +0x80\ngithub.com/matrix-org/util.Protect.func1.1(0x2d3e980, 0x153aad8, 0x2d5e320)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:98 +0xfc\npanic(0x149ce20, 0x1868838)\n\t/usr/lib/go/src/runtime/panic.go:969 +0x168\ngithub.com/matrix-org/dendrite/roomserver/api.IsServerBannedFromRoom(0x153b9f8, 0x2eeb120, 0x0, 0x0, 0x314c1a0, 0x11, 0x2d5a151, 0xf, 0xce7ae8)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/roomserver/api/wrapper.go:165 +0x90\ngithub.com/matrix-org/dendrite/federationapi/routing.Setup.func5(0x2d3ea00, 0x2f94420, 0x2eeb2c0, 0x0, 0x2eeb120, 0x2d5a151, 0xf)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/federationapi/routing/routing.go:123 +0xdc\ngithub.com/matrix-org/dendrite/internal/httputil.MakeFedAPI.func1(0x2d3ea00, 0x0, 0x0, 0x0, 0x0)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/internal/httputil/httpapi.go:204 +0x1a4\ngithub.com/matrix-org/util.(*jsonRequestHandlerWrapper).OnIncomingRequest(0x2c10dd8, 0x2d3ea00, 0x300, 0xbec100, 0xe7a230f8, 0x44)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:79 +0x28\ngithub.com/matrix-org/util.MakeJSONAPI.func1(0x153aad8, 0x2d5e320, 0x2d3ea00)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:141 +0x5c\ngithub.com/matrix-org/util.Protect.func1(0x153aad8, 0x2d5e320, 0x2d3e980)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:103 +0x68\nnet/http.HandlerFunc.ServeHTTP(...)\n\t/usr/lib/go/src/net/http/server.go:2042\ngithub.com/matrix-org/dendrite/internal/httputil.MakeExternalAPI.func1(0x153aad8, 0x2d5e320, 0x2d3e900)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/internal/httputil/httpapi.go:123 +0x1b0\nnet/http.HandlerFunc.ServeHTTP(0x2eb4ee0, 0x153aad8, 0x2d5e320, 0x2d3e900)\n\t/usr/lib/go/src/net/http/server.go:2042 +0x34\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0x2ce1b00, 0x153aad8, 0x2d5e320, 0x2d3e800)\n\t/home/buildozer/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x9c\nnet/http.serverHandler.ServeHTTP(0x2cc8510, 0x153aad8, 0x2d5e320, 0x2d3e800)\n\t/usr/lib/go/src/net/http/server.go:2843 +0x90\nnet/http.(*conn).serve(0x2eee1e0, 0x153b998, 0x2eea140)\n\t/usr/lib/go/src/net/http/server.go:1925 +0x834\ncreated by net/http.(*Server).Serve\n\t/usr/lib/go/src/net/http/server.go:2969 +0x314\n" func="1\n\t" file=" [/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:97]" context=missing panic="runtime error: invalid memory address or nil pointer dereference"
time="2020-11-16T22:52:04.427962939Z" level=warning msg="incoming federation request failed to notify server alive" func="Wakeup\n\t" file=" [/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/internal/httputil/httpapi.go:229]" error="Post \"http://localhost:7775/api/federationsender/performServersAlive\": dial tcp [::1]:7775: connect: connection refused" origin="localhost:36351" req.id=GnB7D2M3mxG3 req.method=PUT req.path="/_matrix/federation/v2/invite/!roomid:localhost/$OzENBCuVv/fnRAYCeQudIon/84/V5pxtEjQMTgi3emk"
time="2020-11-16T22:52:04.430397097Z" level=error msg="Request panicked!\ngoroutine 147 [running]:\nruntime/debug.Stack(0x2d25100, 0x32f57fc, 0x2d25140)\n\t/usr/lib/go/src/runtime/debug/stack.go:24 +0x80\ngithub.com/matrix-org/util.Protect.func1.1(0x2cd2900, 0x153aad8, 0x2e80000)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:98 +0xfc\npanic(0x149ce20, 0x1868838)\n\t/usr/lib/go/src/runtime/panic.go:969 +0x168\ngithub.com/matrix-org/dendrite/roomserver/api.IsServerBannedFromRoom(0x153b9f8, 0x2e03880, 0x0, 0x0, 0x2ec1d00, 0x11, 0x2cce291, 0xf, 0xce7ae8)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/roomserver/api/wrapper.go:165 +0x90\ngithub.com/matrix-org/dendrite/federationapi/routing.Setup.func5(0x2cd2980, 0x2e0bf80, 0x2e03980, 0x0, 0x2e03880, 0x2cce291, 0xf)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/federationapi/routing/routing.go:123 +0xdc\ngithub.com/matrix-org/dendrite/internal/httputil.MakeFedAPI.func1(0x2cd2980, 0x0, 0x0, 0x0, 0x0)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/internal/httputil/httpapi.go:204 +0x1a4\ngithub.com/matrix-org/util.(*jsonRequestHandlerWrapper).OnIncomingRequest(0x2c10dd8, 0x2cd2980, 0x300, 0xbec100, 0xe7acef18, 0x44)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:79 +0x28\ngithub.com/matrix-org/util.MakeJSONAPI.func1(0x153aad8, 0x2e80000, 0x2cd2980)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:141 +0x5c\ngithub.com/matrix-org/util.Protect.func1(0x153aad8, 0x2e80000, 0x2cd2900)\n\t/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:103 +0x68\nnet/http.HandlerFunc.ServeHTTP(...)\n\t/usr/lib/go/src/net/http/server.go:2042\ngithub.com/matrix-org/dendrite/internal/httputil.MakeExternalAPI.func1(0x153aad8, 0x2e80000, 0x2cd2880)\n\t/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/internal/httputil/httpapi.go:123 +0x1b0\nnet/http.HandlerFunc.ServeHTTP(0x2eb4ee0, 0x153aad8, 0x2e80000, 0x2cd2880)\n\t/usr/lib/go/src/net/http/server.go:2042 +0x34\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0x2ce1b00, 0x153aad8, 0x2e80000, 0x3008000)\n\t/home/buildozer/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x9c\nnet/http.serverHandler.ServeHTTP(0x2cc8510, 0x153aad8, 0x2e80000, 0x3008000)\n\t/usr/lib/go/src/net/http/server.go:2843 +0x90\nnet/http.(*conn).serve(0x2eee1e0, 0x153b998, 0x2eea140)\n\t/usr/lib/go/src/net/http/server.go:1925 +0x834\ncreated by net/http.(*Server).Serve\n\t/usr/lib/go/src/net/http/server.go:2969 +0x314\n" func="1\n\t" file=" [/home/buildozer/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:97]" context=missing panic="runtime error: invalid memory address or nil pointer dereference"
time="2020-11-16T22:52:04.431542626Z" level=warning msg="incoming federation request failed to notify server alive" func="Wakeup\n\t" file=" [/builds/6543/aports/testing/dendrite/src/dendrite-0.3.0/internal/httputil/httpapi.go:229]" error="Post \"http://localhost:7775/api/federationsender/performServersAlive\": dial tcp [::1]:7775: connect: connection refused" origin="localhost:36351" req.id=OuPu3Ub78MCt req.method=PUT req.path="/_matrix/federation/v2/invite/!roomid:localhost/$EmwNBlHoSOVmCZ1cM//yv/OvxB6r4OFEIGSJea7+Amk"
--- FAIL: TestRoomsV3URLEscapeDoNot404 (52.56s)
    federationapi_test.go:87: failed to cast response error as gomatrix.HTTPError
    federationapi_test.go:90: Error: contents=[123 34 109 101 115 115 97 103 101 34 58 34 73 110 116 101 114 110 97 108 32 83 101 114 118 101 114 32 69 114 114 111 114 34 125] msg=Failed to PUT JSON (hostname "localhost:36351" path "/_matrix/federation/v2/invite/!roomid:localhost/$0SFh2WJbjBs3OT+E0yl95giDKo/3Zp52HsHUUk4uPyg"): {"message":"Internal Server Error"} code=500 wrapped=
    federationapi_test.go:90: Error: contents=[123 34 109 101 115 115 97 103 101 34 58 34 73 110 116 101 114 110 97 108 32 83 101 114 118 101 114 32 69 114 114 111 114 34 125] msg=Failed to PUT JSON (hostname "localhost:36351" path "/_matrix/federation/v2/invite/!roomid:localhost/$OzENBCuVv/fnRAYCeQudIon/84/V5pxtEjQMTgi3emk"): {"message":"Internal Server Error"} code=500 wrapped=
    federationapi_test.go:90: Error: contents=[123 34 109 101 115 115 97 103 101 34 58 34 73 110 116 101 114 110 97 108 32 83 101 114 118 101 114 32 69 114 114 111 114 34 125] msg=Failed to PUT JSON (hostname "localhost:36351" path "/_matrix/federation/v2/invite/!roomid:localhost/$EmwNBlHoSOVmCZ1cM//yv/OvxB6r4OFEIGSJea7+Amk"): {"message":"Internal Server Error"} code=500 wrapped=
FAIL
FAIL	github.com/matrix-org/dendrite/federationapi
```

**Comment by neilalexander** [comment]
How are you starting the tests?

**Comment by 6543** [comment]
`go test ./...`

**Comment by Kegsay** [comment]
That test listens on a local port to hit it with HTTP requests to check URL escaping is done correctly. It sounds like this CI machine has some sort of networking issue which led to the test failing.

**Comment by 6543** [comment]
Ok Since thiss issue is solved on our side, is this trace worth keeping it open or should we close?

**Comment by neilalexander** [comment]
Thanks for letting us know. We'll close.
