### ISSUE TITLE
`event_id` field missing from room events

### ISSUE THREAD

**Issue by RobinJ1995** [matrix-org/dendrite#1598]
### Background information

- **Dendrite version or git SHA**:  `matrixdotorg/dendrite-monolith:v0.3.1` Docker image
- **Monolith or Polylith?**:  Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Docker + Kubernetes
- **`go version`**: Whatever version you guys used to build the binaries included in [the `matrixdotorg/dendrite-monolith:v0.3.1` Docker image](https://hub.docker.com/r/matrixdotorg/dendrite-monolith) :)

### Description

Dendrite appears to not include the `event_id` field where it is expected.

### Steps to reproduce

1. Setup a clean Dendrite server
2. Setup the [mautrix-telegram](https://github.com/tulir/mautrix-telegram) bridge as an appservice.
3. Start the bridge
4. Send a message to the bridge appservice's bot

The bridge fails to process the event, as it expects an `event_id` field but there is none;
```
[2020-11-24 13:59:03,987] [ERROR@mau.as] Failed to deserialize event {'auth_events': [...], 'content': {'avatar_url': '<REDACTED>', 'displayname': '<REDACTED>', 'membership': 'invite'}, 'depth': 8, 'hashes': {'sha256': '<REDACTED>'}, 'origin': '<REDACTED>', 'origin_server_ts': 1606226343801, 'prev_events': ['$Il-sYK_ZauuAQ40yUForENsgTAXVF14-FNY0Uvg8HX8'], 'prev_state': [], 'room_id': '!muukzTXKlWWTDwM6:<REDACTED>', 'sender': '@robinj1995:<REDACTED>', 'signatures': {...}, 'state_key': '@bridge_telegram:<REDACTED>', 'type': 'm.room.member', 'unsigned': {'age': 163, 'invite_room_state': [{'content': {...}, 'sender': '@robinj1995:<REDACTED>', 'state_key': '@bridge_telegram:<REDACTED>', 'type': 'm.room.member'}, {'content': {'join_rule': 'invite'}, 'sender': '@robinj1995:<REDACTED>', 'state_key': '', 'type': 'm.room.join_rules'}, {'content': {'name': 'ADMIN_BRIDGE_TELEGRAM'}, 'sender': '@robinj1995:<REDACTED>', 'state_key': '', 'type': 'm.room.name'}, {'content': {...}, 'sender': '@robinj1995:<REDACTED>', 'state_key': '@bridge_telegram:<REDACTED>', 'type': 'm.room.member'}]}}
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 117, in _dict_to_attrs
    obj = attrs_type(**new_items)
TypeError: __init__() missing 1 required positional argument: 'event_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/appservice/as_handler.py", line 165, in handle_transaction
    event = Event.deserialize(raw_event)
  File "/usr/lib/python3.8/site-packages/mautrix/types/event/generic.py", line 47, in deserialize_event
    return StateEvent.deserialize(data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/event/state.py", line 214, in deserialize
    return super().deserialize(data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 282, in deserialize
    return _dict_to_attrs(cls, data)
  File "/usr/lib/python3.8/site-packages/mautrix/types/util/serializable_attrs.py", line 122, in _dict_to_attrs
    raise SerializerError(
mautrix.types.util.serializable.SerializerError: Missing value for required key event_id in StateEvent
```

I have first reported this issue on the mautrix-telegram bridge, and [the developer claims](https://github.com/tulir/mautrix-telegram/issues/548#issuecomment-733005500)  that this is an issue with Dendrite, and linked to the to [the room event spec](https://matrix.org/docs/spec/client_server/latest#room-event-fields) which confirms that `event_id` is a required field.

**Comment by S7evinK** [comment]
Probably because of https://github.com/matrix-org/gomatrixserverlib/pull/236

**Comment by RobinJ1995** [comment]
> Probably because of [matrix-org/gomatrixserverlib#236](https://github.com/matrix-org/gomatrixserverlib/pull/236)

That looks like it would just hide the field if it's already empty, though. I'm guessing the underlying issue is its lack of a value?
