### ISSUE TITLE
Concurrent map write in sync API causes crash

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/dendrite#1633]
```
Dec 11 19:37:46 dryad dendrite[13598]: fatal error: concurrent map iteration and map write
Dec 11 19:37:46 dryad dendrite[13598]: goroutine 11368038 [running]:
Dec 11 19:37:46 dryad dendrite[13598]: runtime.throw(0x10f0bf3, 0x26)
Dec 11 19:37:46 dryad dendrite[13598]: #011runtime/panic.go:1112 +0x72 fp=0xc0162ca460 sp=0xc0162ca430 pc=0x43ce12
Dec 11 19:37:46 dryad dendrite[13598]: runtime.mapiternext(0xc0162ca548)
Dec 11 19:37:46 dryad dendrite[13598]: #011runtime/map.go:853 +0x552 fp=0xc0162ca4e0 sp=0xc0162ca460 pc=0x417ed2
Dec 11 19:37:46 dryad dendrite[13598]: runtime.mapiterinit(0xf64140, 0xc002b73c20, 0xc0162ca548)
Dec 11 19:37:46 dryad dendrite[13598]: #011runtime/map.go:843 +0x1c4 fp=0xc0162ca500 sp=0xc0162ca4e0 pc=0x417884
Dec 11 19:37:46 dryad dendrite[13598]: github.com/matrix-org/dendrite/syncapi/types.(*StreamingToken).IsAfter(0xc0003a52b0, 0x24dbb, 0x4bc, 0xc00, 0x0, 0xc0234eae70, 0xc023eac101)
Dec 11 19:37:46 dryad dendrite[13598]: #011github.com/matrix-org/dendrite/syncapi/types/types.go:159 +0xc0 fp=0xc0162ca5b8 sp=0xc0162ca500 pc=0xc9b760
Dec 11 19:37:46 dryad dendrite[13598]: github.com/matrix-org/dendrite/syncapi/sync.(*UserDeviceStreamListener).GetNotifyChannel(0xc0162ca800, 0x24dbb, 0x4bc, 0xc00, 0x0, 0xc0234eae70, 0x0)
Dec 11 19:37:46 dryad dendrite[13598]: #011github.com/matrix-org/dendrite/syncapi/sync/userstream.go:139 +0xab fp=0xc0162ca620 sp=0xc0162ca5b8 pc=0xcd890b
Dec 11 19:37:46 dryad dendrite[13598]: github.com/matrix-org/dendrite/syncapi/sync.(*RequestPool).OnIncomingSyncRequest(0xc0003a4180, 0xc00035d400, 0xc0000f6700, 0x0, 0x0, 0x0, 0x0)
Dec 11 19:37:46 dryad dendrite[13598]: #011github.com/matrix-org/dendrite/syncapi/sync/requestpool.go:161 +0xaf9 fp=0xc0162cb480 sp=0xc0162ca620 pc=0xcd4699
Dec 11 19:37:46 dryad dendrite[13598]: github.com/matrix-org/dendrite/syncapi/routing.Setup.func1(0xc00035d400, 0xc0000f6700, 0xf11300, 0x1284fe0, 0x10bbac0, 0xc0000f6770)
Dec 11 19:37:46 dryad dendrite[13598]: #011github.com/matrix-org/dendrite/syncapi/routing/routing.go:46 +0x3e fp=0xc0162cb4c8 sp=0xc0162cb480 pc=0xce58de
```

**Comment by neilalexander** [comment]
Another related thing caught by the race detector:
```
WARNING: DATA RACE
Read at 0x00c000280270 by goroutine 125:
  runtime.mapiterinit()
      /usr/local/go/src/runtime/map.go:797 +0x0
  github.com/matrix-org/dendrite/syncapi/types.(*StreamingToken).WithUpdates()
      /Users/neilalexander/Desktop/dendrite/syncapi/types/types.go:192 +0x151
  github.com/matrix-org/dendrite/syncapi/sync.(*Notifier).OnNewEvent()
      /Users/neilalexander/Desktop/dendrite/syncapi/sync/notifier.go:80 +0x145
  github.com/matrix-org/dendrite/syncapi/consumers.(*OutputRoomEventConsumer).onNewRoomEvent()
      /Users/neilalexander/Desktop/dendrite/syncapi/consumers/roomserver.go:184 +0xa49
  github.com/matrix-org/dendrite/syncapi/consumers.(*OutputRoomEventConsumer).onMessage()
      /Users/neilalexander/Desktop/dendrite/syncapi/consumers/roomserver.go:99 +0xa17
  github.com/matrix-org/dendrite/syncapi/consumers.(*OutputRoomEventConsumer).onMessage-fm()
      /Users/neilalexander/Desktop/dendrite/syncapi/consumers/roomserver.go:78 +0x4b
  github.com/matrix-org/dendrite/internal.(*ContinualConsumer).consumePartition()
      /Users/neilalexander/Desktop/dendrite/internal/consumers.go:112 +0x141

Previous write at 0x00c000280270 by goroutine 158:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:202 +0x0
  github.com/matrix-org/dendrite/syncapi/types.(*StreamingToken).SetLog()
      /Users/neilalexander/Desktop/dendrite/syncapi/types/types.go:120 +0xdca
  github.com/matrix-org/dendrite/syncapi/internal.DeviceListCatchup()
      /Users/neilalexander/Desktop/dendrite/syncapi/internal/keychange.go:133 +0xcc9
  github.com/matrix-org/dendrite/syncapi/sync.(*RequestPool).appendDeviceLists()
      /Users/neilalexander/Desktop/dendrite/syncapi/sync/requestpool.go:313 +0x1d0
  github.com/matrix-org/dendrite/syncapi/sync.(*RequestPool).currentSyncForUser()
      /Users/neilalexander/Desktop/dendrite/syncapi/sync/requestpool.go:274 +0xd09
  github.com/matrix-org/dendrite/syncapi/sync.(*RequestPool).OnIncomingSyncRequest()
      /Users/neilalexander/Desktop/dendrite/syncapi/sync/requestpool.go:181 +0x1330
  github.com/matrix-org/dendrite/syncapi/routing.Setup.func1()
      /Users/neilalexander/Desktop/dendrite/syncapi/routing/routing.go:46 +0x59
  github.com/matrix-org/dendrite/internal/httputil.MakeAuthAPI.func1()
      /Users/neilalexander/Desktop/dendrite/internal/httputil/httpapi.go:63 +0x45d
  github.com/matrix-org/util.(*jsonRequestHandlerWrapper).OnIncomingRequest()
      /Users/neilalexander/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:79 +0x54
  github.com/matrix-org/util.MakeJSONAPI.func1()
      /Users/neilalexander/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:141 +0xca
  github.com/matrix-org/util.Protect.func1()
      /Users/neilalexander/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:103 +0xd8
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2042 +0x354
  github.com/matrix-org/dendrite/internal/httputil.MakeExternalAPI.func1()
      /Users/neilalexander/Desktop/dendrite/internal/httputil/httpapi.go:123 +0x7e
  net/http.HandlerFunc.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2042 +0x51
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /Users/neilalexander/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x132
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /Users/neilalexander/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x132
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2843 +0xca
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1925 +0x84c

Goroutine 125 (running) created at:
  github.com/matrix-org/dendrite/internal.(*ContinualConsumer).StartOffsets()
      /Users/neilalexander/Desktop/dendrite/internal/consumers.go:102 +0x77b
  github.com/matrix-org/dendrite/internal.(*ContinualConsumer).Start()
      /Users/neilalexander/Desktop/dendrite/internal/consumers.go:62 +0xa6b
  github.com/matrix-org/dendrite/syncapi/consumers.(*OutputRoomEventConsumer).Start()
      /Users/neilalexander/Desktop/dendrite/syncapi/consumers/roomserver.go:72 +0xa48
  github.com/matrix-org/dendrite/syncapi.AddPublicRoutes()
      /Users/neilalexander/Desktop/dendrite/syncapi/syncapi.go:77 +0xa76
  github.com/matrix-org/dendrite/setup.(*Monolith).AddAllPublicRoutes()
      /Users/neilalexander/Desktop/dendrite/setup/monolith.go:72 +0x795
  main.main()
      /Users/neilalexander/Desktop/dendrite/cmd/dendrite-demo-yggdrasil/main.go:151 +0x188d

Goroutine 158 (running) created at:
  net/http.(*Server).Serve()
      /usr/local/go/src/net/http/server.go:2969 +0x5d3
  net/http.(*Server).ListenAndServe()
      /usr/local/go/src/net/http/server.go:2866 +0x105
  net/http.ListenAndServe()
      /usr/local/go/src/net/http/server.go:3120 +0x25d
  main.main.func4()
      /Users/neilalexander/Desktop/dendrite/cmd/dendrite-demo-yggdrasil/main.go:191 +0x268
```
