### ISSUE TITLE
Bridging messages with Mautrix-Whatsapp fails due to an appservices permission problem

### ISSUE THREAD

**Issue by phol** [matrix-org/dendrite#1711]
### Background information

- **Dendrite version or git SHA**: v0.3.5 with manually applied #1684 
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: no
- **`go version`**: `go1.15.2 linux/amd64`

### Description

Dendrite doesn't give appservices sufficient permissions.

### Steps to reproduce

- Install Dendrite and Mautrix-Whatsapp. Register mautrix-whatsapp as appservice in dendrite.
- After patching with #1684, you'll be able to login to your whatsapp account, the appservice responds to events.

- Login and try to sync messages using the `sync` command.
- Syncing should start but nothing happens.

### Logs

- Dendrite

```log
time="2021-01-14T17:04:30.331340796Z" level=info msg="Error authing soft-failed event" func="processRoomEvent\n\t" file=" [/opt/dendrite/roomserver/internal/input/input_events.go:90]" error="eventauth: \"@whatsappbot:example.org\" is not allowed to change their membership from \"leave\" to \"join\"" event_id="*" room="*:example.org" type=m.room.member
time="2021-01-14T17:04:30.367828626Z" level=info msg="Producing to topic 'DendriteOutputRoomEvent'" func="WriteOutputEvents\n\t" file=" [/opt/dendrite/roomserver/internal/input/input.go:101]" adds_state=1 event_id="*" event_type=m.room.member removes_state=1 room_id="*:example.org" send_as_server=example.org sender="@whatsappbot:example.org" type=new_room_event
time="2021-01-14T17:04:30.371950516Z" level=error msg="SendEvents failed" func="SetDisplayName\n\t" file=" [/opt/dendrite/clientapi/routing/profile.go:292]" error="eventauth: eventauth: \"@whatsappbot:example.org\" is not allowed to change their membership from \"leave\" to \"join\"" req.id=GyOY7C9PKhJd req.method=PUT req.path="/_matrix/client/r0/profile/@whatsappbot:example.org/displayname" user_id="@whatsappbot:example.org"
time="2021-01-14T17:04:33.016852241Z" level=error msg="helpers.CheckAuthEvents failed for event, rejecting event" func="processRoomEvent\n\t" file=" [/opt/dendrite/roomserver/internal/input/input_events.go:76]" auth_event_ids="[* * *]" error="eventauth: \"@whatsappbot:example.org\" is not allowed to change their membership from \"leave\" to \"join\"" event_id="*"
```

- Mautrix-WhatsApp

```log
[Jan 14, 2021 17:48:37] [User/@exampleuser:example.org/DEBUG] Processing of incoming messages is locked
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xaf32d2]
goroutine 100 [running]:
main.(*User).createCommunity(0xc00047f900)
         /builds/tulir/mautrix-whatsapp/community.go:66 +0x4b2
main.(*User).intPostLogin(0xc00047f900)
       /builds/tulir/mautrix-whatsapp/user.go:497 +0xbf
created by main.(*User).PostLogin
       /builds/tulir/mautrix-whatsapp/user.go:423 +0x170

Jan 14 17:48:37 dendrite systemd[1]: mautrix-whatsapp.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 14 17:48:37 dendrite systemd[1]: mautrix-whatsapp.service: Failed with result 'exit-code'.
````

**Comment by phol** [comment]
Based on a comment from @tulir on [tulir/mautrix-whatsapp#257](https://github.com/tulir/mautrix-whatsapp/issues/257), I disabled the creation of communities in the Mautrix-WhatsApp config.yaml. The error was thrown because Dendrite does not seem to support communities yet.

I'm unaware if in Dendrite, communities have been implemented at all or if this is an appservices related issue.
If it is the former, please feel free to close this issue. In that case I can create a new one about communities support.

**Comment by Kegsay** [comment]
Dendrite does not implement Communities and only has partial AS support as it is.
