### ISSUE TITLE
0.3.10 panic: send on closed channel

### ISSUE THREAD

**Issue by ptman** [matrix-org/dendrite#1770]
### Background information

- **Dendrite version or git SHA**: 0.3.10
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: yes
- **`go version`**:  whatever matrixdotorg/dendrite-monolith uses

### Description

panic: send on closed channel

### Steps to reproduce

I just run dendrite and get this:

```
panic: send on closed channel

goroutine 65 [running]:
github.com/matrix-org/dendrite/federationsender/queue.(*destinationQueue).sendEDU(0xc00026e690, 0xc00007f810, 0xc0004300b0)
        github.com/matrix-org/dendrite/federationsender/queue/destinationqueue.go:151 +0x21c
github.com/matrix-org/dendrite/federationsender/queue.(*OutgoingQueues).SendEDU(0xc000121e30, 0xc00007f810, 0xc0002102c0, 0xb, 0xc0004f6000, 0x9ae, 0xa00, 0x9ae, 0xa00)
        github.com/matrix-org/dendrite/federationsender/queue/queue.go:326 +0x849
github.com/matrix-org/dendrite/federationsender/consumers.(*KeyChangeConsumer).onMessage(0xc00010bb80, 0xc00057c0a0, 0x1, 0x101)
        github.com/matrix-org/dendrite/federationsender/consumers/keychange.go:133 +0xb3d
github.com/matrix-org/dendrite/internal.(*ContinualConsumer).consumePartition(0xc000100660, 0x12e6fc0, 0xc00027c3e0)
        github.com/matrix-org/dendrite/internal/consumers.go:126 +0xe2
created by github.com/matrix-org/dendrite/internal.(*ContinualConsumer).StartOffsets
        github.com/matrix-org/dendrite/internal/consumers.go:107 +0x545
```

**Comment by ptman** [comment]
4c0103a2 seems to have fixed this
