### ISSUE TITLE
federationsender: database locked when starting new conversation causing crash

### ISSUE THREAD

**Issue by andir** [matrix-org/dendrite#1786]
### Background information

- **Dendrite version or git SHA**: 9557ccada4efe50d0f370019ad0b9f017fc7ebcf
- monolith
- sqlite3
- Running in Docker: no
- Go 1.15

### Description

I started a conversation with a remote server that I never before had contacted. I just used element to create the conversation and after having invited the other party my homeserver died with the below logs.

```
Mar 04 13:01:32 kack dendrite-start[5812]: time="2021-03-04T13:01:32.682421912Z" level=panic msg="roomserver output log: write room event failure" func="onMessage\n\t" file=" [/build/dendrite-src/federationsender/consumers/roomserver.go:113]" add="[$gU-AV-6Nm2w6mxNWNMX6kvQ3fgII3ROkCT0zDT4HRI8]" del="[]" error="database is locked" event="{\"auth_events\":[\"$fMW7cNEWxt7ecwnxXrcJx8fe374UPuqv_lA4mLzsvHc\",\"$o155WJ7fiJlI7ul2zbaIiTA34EWr-UBMIhqdPam_0Ds\",\"$L7OV0jTwT0oKHbCQleyoqCbnlSsa4LSLZa9PdTBA8S8\"],\"content\":{\"is_direct\":true,\"membership\":\"invite\"},\"depth\":8,\"hashes\":{\"sha256\":\"VdNEyDoPC6UTc98s+BkHtoF2ZA/N3kNpdoJzToUgI7I\"},\"origin\":\"kack.it\",\"origin_server_ts\":1614862884581,\"prev_events\":[\"$icyY-jjFgUmToMKRc9mNPwYnvVne6wOljyxH_b9kAjM\"],\"prev_state\":[],\"room_id\":\"!Pcrlaz6GN2naKmUg:kack.it\",\"sender\":\"@andi:kack.it\",\"state_key\":\"@user:otherserver.com\",\"type\":\"m.room.member\",\"signatures\":{\"kack.it\":{\"ed25519:ebq842\":\"Dd1Ru7HJMNjedy8hICJNmygyMppCzE3PrUbRcraOrlWACEMlOvknOexd5zQrtm9XrN2WicrgknNBXueVPGpaAQ\"},\"otherserver.com\":{\"ed25519:a_tZLy\":\"0OIUd5Vy8WO+ychuyfytBVr/………0ry+lD5WVZW+QLy3mVDQ\"}},\"unsigned\":{\"invite_room_state\":[{\"content\":{\"displayname\":\"andi\",\"membership\":\"join\"},\"state_key\":\"@andi:kack.it\",\"type\":\"m.room.member\",\"sender\":\"@andi:kack.it\"},{\"content\":{\"join_rule\":\"invite\"},\"state_key\":\"\",\"type\":\"m.room.join_rules\",\"sender\":\"@andi:kack.it\"},{\"content\":{\"algorithm\":\"m.megolm.v1.aes-sha2\"},\"state_key\":\"\",\"type\":\"m.room.encryption\",\"sender\":\"@andi:kack.it\"},{\"content\":{\"is_direct\":true,\"membership\":\"invite\"},\"state_key\":\"@user:otherserver.com\",\"type\":\"m.room.member\",\"sender\":\"@andi:kack.it\"}]}}" event_id="$gU-AV-6Nm2w6mxNWNMX6kvQ3fgII3ROkCT0zDT4HRI8"
Mar 04 13:01:32 kack dendrite-start[5812]: panic: (*logrus.Entry) 0xc00032e460
Mar 04 13:01:32 kack dendrite-start[5812]: goroutine 10 [running]:
Mar 04 13:01:32 kack dendrite-start[5812]: github.com/sirupsen/logrus.(*Entry).log(0xc00032e3f0, 0x0, 0xc002def680, 0x2f)
Mar 04 13:01:32 kack dendrite-start[5812]:         /build/dendrite-src/vendor/github.com/sirupsen/logrus/entry.go:259 +0x2e5
Mar 04 13:01:32 kack dendrite-start[5812]: github.com/sirupsen/logrus.(*Entry).Log(0xc00032e3f0, 0x0, 0xc0048899a8, 0x1, 0x1)
Mar 04 13:01:32 kack dendrite-start[5812]:         /build/dendrite-src/vendor/github.com/sirupsen/logrus/entry.go:285 +0x86
Mar 04 13:01:32 kack dendrite-start[5812]: github.com/sirupsen/logrus.(*Entry).Logf(0xc00032e3f0, 0xc000000000, 0x11b41b7, 0x2f, 0x0, 0x0, 0x0)
Mar 04 13:01:32 kack dendrite-start[5812]:         /build/dendrite-src/vendor/github.com/sirupsen/logrus/entry.go:330 +0xe5
Mar 04 13:01:32 kack dendrite-start[5812]: github.com/sirupsen/logrus.(*Entry).Panicf(...)
Mar 04 13:01:32 kack dendrite-start[5812]:         /build/dendrite-src/vendor/github.com/sirupsen/logrus/entry.go:368
Mar 04 13:01:32 kack dendrite-start[5812]: github.com/matrix-org/dendrite/federationsender/consumers.(*OutputRoomEventConsumer).onMessage(0xc00035b3c0, 0xc004bc9680, 0x1, 0x101)
Mar 04 13:01:32 kack dendrite-start[5812]:         /build/dendrite-src/federationsender/consumers/roomserver.go:113 +0x6f1
Mar 04 13:01:32 kack dendrite-start[5812]: github.com/matrix-org/dendrite/internal.(*ContinualConsumer).consumePartition(0xc00043ecc0, 0x13156c0, 0xc0004407e0)
Mar 04 13:01:32 kack dendrite-start[5812]:         /build/dendrite-src/internal/consumers.go:126 +0xe2
Mar 04 13:01:32 kack dendrite-start[5812]: created by github.com/matrix-org/dendrite/internal.(*ContinualConsumer).StartOffsets
Mar 04 13:01:32 kack dendrite-start[5812]:         /build/dendrite-src/internal/consumers.go:107 +0x545
Mar 04 13:01:32 kack systemd[1]: dendrite.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

### Steps to reproduce

I can't reproduce it after the initial crash :(

**Comment by Kegsay** [comment]
Can you please confirm that you have a dedicated `.db` file for `federationsender` e.g something like `file:fedsender.db`? And that it is not used by any other component?

**Comment by andir** [comment]
Yeah, as far as I can tell each of the services has a dedicated DB. You can see my configuration here: https://github.com/andir/infra/blob/15aac8d0c180c87a92161d5e6d8ae7aee21aeb06/config/modules/dendrite.nix#L5-L214 (This expression generates the JSON file).

**Comment by Jaedotmoe** [comment]
I have the same error running the latest Dendrite version at the time (0.3.11) on Docker.
```
dendrite_1    | panic: (*logrus.Entry) 0xc00021f960
dendrite_1    |
dendrite_1    | goroutine 40 [running]:
dendrite_1    | github.com/sirupsen/logrus.Entry.log(0xc000158c40, 0xc00020f2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
dendrite_1    | 	github.com/sirupsen/logrus@v1.7.0/entry.go:255 +0x325
dendrite_1    | github.com/sirupsen/logrus.(*Entry).Log(0xc00021f8f0, 0x0, 0xc0000f39a8, 0x1, 0x1)
dendrite_1    | 	github.com/sirupsen/logrus@v1.7.0/entry.go:283 +0xf0
dendrite_1    | github.com/sirupsen/logrus.(*Entry).Logf(0xc00021f8f0, 0xc000000000, 0x118d600, 0x2f, 0x0, 0x0, 0x0)
dendrite_1    | 	github.com/sirupsen/logrus@v1.7.0/entry.go:329 +0xe5
dendrite_1    | github.com/sirupsen/logrus.(*Entry).Panicf(...)
dendrite_1    | 	github.com/sirupsen/logrus@v1.7.0/entry.go:367
dendrite_1    | github.com/matrix-org/dendrite/federationsender/consumers.(*OutputRoomEventConsumer).onMessage(0xc000085280, 0xc0004f63c0, 0x1, 0x101)
dendrite_1    | 	github.com/matrix-org/dendrite/federationsender/consumers/roomserver.go:113 +0x6f1
dendrite_1    | github.com/matrix-org/dendrite/internal.(*ContinualConsumer).consumePartition(0xc0000863c0, 0x12e7fc0, 0xc000448300)
dendrite_1    | 	github.com/matrix-org/dendrite/internal/consumers.go:126 +0xe2
dendrite_1    | created by github.com/matrix-org/dendrite/internal.(*ContinualConsumer).StartOffsets
dendrite_1    | 	github.com/matrix-org/dendrite/internal/consumers.go:107 +0x545
```

**Comment by andir** [comment]
I just connected a third client to my homeserver (same single user) and this happened: 
```
May 19 11:26:18 kack dendrite-start[19980]: time="2021-05-19T11:26:18.599288095Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [/build/dendrite-src/signingkeyserver/internal/api.go:262]" fetcher_name=DirectKeyFetcher
May 19 11:26:18 kack dendrite-start[19980]: panic: the ContinualConsumer in "syncapi/keychange" failed to SetPartitionOffset: database is locked
May 19 11:26:18 kack dendrite-start[19980]: goroutine 106 [running]:
May 19 11:26:18 kack dendrite-start[19980]: github.com/matrix-org/dendrite/internal.(*ContinualConsumer).consumePartition(0xc00012e120, 0x13b16c0, 0xc0003a2420)
May 19 11:26:18 kack dendrite-start[19980]:         /build/dendrite-src/internal/consumers.go:129 +0x2ed
May 19 11:26:18 kack dendrite-start[19980]: created by github.com/matrix-org/dendrite/internal.(*ContinualConsumer).StartOffsets
May 19 11:26:18 kack dendrite-start[19980]:         /build/dendrite-src/internal/consumers.go:107 +0x545
May 19 11:26:18 kack systemd[1]: dendrite.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

Revision: 2948ffd78207e0fd354be9a3a637cfdaa3c5154a

**Comment by neilalexander** [comment]
I don't think this can possibly be relevant anymore, but please reopen if there are still issues on 0.8.1.
