### ISSUE TITLE
"Performing state storage upgrade" on malformed database

### ISSUE THREAD

**Issue by zephryn** [matrix-org/dendrite#2017]
### Background information

- **Dendrite version or git SHA**: 0.5.0
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: sqlite3
- **Running in Docker?**: no
- **`go version`**: `go version go1.17.1 freebsd/amd64`

### Description
after some bad luck with database problems in past versions, i decided to see if dendrite 0.5.0 would react differently. i believe the database became malformed from a previous version of dendrite on more than one occasion (e.g. #1838) but i can't recall what specifically happened or when it occurred.

when starting dendrite, the following was appended to Monolith.log:
```
time="2021-10-06T19:28:24.551586262Z" level=info msg="Dendrite version 0.5.0" func=github.com/matrix-org/dendrite/setup.NewBaseDendrite file="github.com/matrix-org/dendrite/setup/base.go:113"
time="2021-10-06T19:28:24.573180115Z" level=info msg="Enabled perspective key fetcher" func=github.com/matrix-org/dendrite/signingkeyserver.NewInternalAPI file="github.com/matrix-org/dendrite/signingkeyserver/signingkeyserver.go:103" num_public_keys=2 server_name=matrix.org
time="2021-10-06T19:28:24.593136463Z" level=warning msg="Performing state storage upgrade. Please wait, this may take some time!" func=github.com/matrix-org/dendrite/roomserver/storage/sqlite3/deltas.UpStateBlocksRefactor file="github.com/matrix-org/dendrite/roomserver/storage/sqlite3/deltas/2021041615092700_state_blocks_refactor.go:36"
```
i let the process run at 95-100% cpu usage for 3-4 hours(!) before i stopped the service; i recall an earlier version (0.4.1 probably?) logging this same message every 20 minutes or so, but this time no other messages were logged.

putting the database file through `sqlite3_analyzer` resulted in the following error, with sqlitebrowser also returning the same error dialog:
```
ERROR: malformed database schema (roomserver_state_block) - invalid rootpage
malformed database schema (roomserver_state_block) - invalid rootpage
    while executing
"db exists {SELECT 1 FROM pragma_compile_options
                WHERE compile_options='ENABLE_DBSTAT_VTAB'}"
```

i decided to try recovering the database with sqlite once more using the command `sqlite3 /tmp/roomserver.db ".recover" | sqlite3 /tmp/roomserver_new.db`, getting the following output:
```
Error: near line 150693: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 150694: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 150695: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 150696: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 150697: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 150698: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 150699: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 150700: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170193: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170194: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170195: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170196: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170197: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170198: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170199: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170200: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170201: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170202: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170203: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170204: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170205: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170206: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170207: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170208: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170209: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170210: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170211: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170212: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170213: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170214: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170215: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170216: UNIQUE constraint failed: roomserver_events.event_nid
Error: near line 170217: UNIQUE constraint failed: roomserver_events.event_nid
```

afterwards the file appeared to open in sqlitebrowser fine, but running `dendrite-monolith-server` with the new `roomserver.db` didn't go well:
```
INFO[2021-10-07T01:23:35.579501305Z] [base.go:113] NewBaseDendrite
   Dendrite version 0.5.0                       
INFO[2021-10-07T01:23:35.582040087Z] [signingkeyserver.go:103] NewInternalAPI
   Enabled perspective key fetcher               num_public_keys=2 server_name=matrix.org
PANI[2021-10-07T01:23:35.584154097Z] [roomserver.go:54] NewInternalAPI
   failed to connect to room server db           error="RunDeltas: Failed to EnsureDBVersion: failed to scan row: sql: Scan error on column index 0, name \"version_id\": converting driver.Value type []uint8 (\"(json data)\") to a int64: invalid syntax"
panic: (*logrus.Entry) 0xc000223180

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc000223110, 0x0, {0xc0000a88d0, 0x23})
  github.com/sirupsen/logrus/entry.go:259 +0x2a5
github.com/sirupsen/logrus.(*Entry).Log(0xc000223110, 0x0, {0xc0000f1c00, 0x1, 0x1})
  github.com/sirupsen/logrus/entry.go:293 +0x7c
github.com/sirupsen/logrus.(*Entry).Logf(0xc000223110, 0x0, {0x459d47, 0x23}, {0x0, 0x0, 0x0})
  github.com/sirupsen/logrus/entry.go:338 +0xde
github.com/sirupsen/logrus.(*Entry).Panicf(...)
  github.com/sirupsen/logrus/entry.go:376
github.com/matrix-org/dendrite/roomserver.NewInternalAPI(0xc0000b74d0, {0x5c7a80, 0xc000230630})
  github.com/matrix-org/dendrite/roomserver/roomserver.go:54 +0x1a5
main.main()
  github.com/matrix-org/dendrite/cmd/dendrite-monolith-server/main.go:89 +0x515
```

**Comment by kegsay** [comment]
It's expected that the state storage upgrade will take hours on SQLite with a lot of room data. I can't really provide any support here other than letting the upgrade take the time it needs to completion.
