### ISSUE TITLE
process crashed

### ISSUE THREAD

**Issue by catsmeows** [matrix-org/dendrite#2228]
### Background information

- **Dendrite version or git SHA**: 4c07374c42e5d671cfb137634475f43f84f9db0e
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: no
- **`go version`**: go1.16.10
- **Client used (if applicable)**:

### Description

 - **What** is the problem: dendrite crashed
 - **Who** is affected: .
 - **How** is this bug manifesting: unsure
 - **When** did this first appear: unsure

```
goroutine 15867852 [select, 280 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc0022bc1e0)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66



goroutine 18891968 [select]:
net/http.(*persistConn).roundTrip(0xc003118d80, 0xc00feaad80, 0x0, 0x0, 0x0)
	net/http/transport.go:2610 +0x765
net/http.(*Transport).roundTrip(0xc00e725900, 0xc004594300, 0xc000222878, 0x12d1901, 0xc01427e750)
	net/http/transport.go:592 +0xacb
net/http.(*Transport).RoundTrip(0xc00e725900, 0xc004594300, 0x12, 0x16b59a0, 0xc00e725900)
	net/http/roundtrip.go:17 +0x35
github.com/matrix-org/gomatrixserverlib.(*federationTripper).RoundTrip(0xc000222870, 0xc004594300, 0xc000222870, 0xc07e91029d5b4340, 0x440f7b4b77cc)
	github.com/matrix-org/gomatrixserverlib@v0.0.0-20220224170509-f6ab9c54d052/client.go:236 +0x20e
net/http.send(0xc004594200, 0x16b49c0, 0xc000222870, 0xc07e91029d5b4340, 0x440f7b4b77cc, 0x1e50440, 0xc0384b61b0, 0xc07e91029d5b4340, 0x1, 0x0)
	net/http/client.go:251 +0x454
net/http.(*Client).send(0xc000270980, 0xc004594200, 0xc07e91029d5b4340, 0x440f7b4b77cc, 0x1e50440, 0xc0384b61b0, 0x0, 0x1, 0x68)
	net/http/client.go:175 +0xff
net/http.(*Client).do(0xc000270980, 0xc004594200, 0x0, 0x0, 0x0)
	net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	net/http/client.go:585
github.com/matrix-org/gomatrixserverlib.(*Client).DoHTTPRequest(0xc000270980, 0x16d27e8, 0xc0279433e0, 0xc004594100, 0x56, 0xe, 0x33)
	github.com/matrix-org/gomatrixserverlib@v0.0.0-20220224170509-f6ab9c54d052/client.go:518 +0x455
github.com/matrix-org/gomatrixserverlib.(*Client).DoRequestAndParseResponse(0xc000270980, 0x16d27e8, 0xc0279433e0, 0xc004594100, 0x1295d00, 0xc0317b8a98, 0x0, 0x0)
	github.com/matrix-org/gomatrixserverlib@v0.0.0-20220224170509-f6ab9c54d052/client.go:454 +0x85
github.com/matrix-org/gomatrixserverlib.(*FederationClient).doRequest(0xc000270980, 0x16d27e8, 0xc0279433e0, 0xc0201cecc0, 0x33, 0x40, 0xc0217d6f4f, 0xb, 0x14e5583, 0x4, ...)
	github.com/matrix-org/gomatrixserverlib@v0.0.0-20220224170509-f6ab9c54d052/federationclient.go:50 +0x15d
github.com/matrix-org/gomatrixserverlib.(*FederationClient).QueryKeys(0xc000270980, 0x16d27e8, 0xc0279433e0, 0xc0217d6f4f, 0xb, 0xc003e42510, 0xc07e90b79d58719b, 0x43c9a1e3ee28, 0x1e50440, 0x0, ...)
	github.com/matrix-org/gomatrixserverlib@v0.0.0-20220224170509-f6ab9c54d052/federationclient.go:456 +0x2d4
github.com/matrix-org/dendrite/federationapi/internal.(*FederationInternalAPI).QueryKeys.func1(0xc0005ac460, 0xc0217d6f4f, 0xb, 0xc002c38420)
	github.com/matrix-org/dendrite/federationapi/internal/federationclient.go:60 +0x6d
github.com/matrix-org/dendrite/federationapi/internal.(*FederationInternalAPI).doRequestIfNotBackingOffOrBlacklisted(0xc0005ac460, 0xc0217d6f4f, 0xb, 0xc00261da10, 0x18, 0xc0317b8a68, 0x0, 0xc002306800)
	github.com/matrix-org/dendrite/federationapi/internal/api.go:152 +0x87
github.com/matrix-org/dendrite/federationapi/internal.(*FederationInternalAPI).QueryKeys(0xc0005ac460, 0x16d27e8, 0xc0279433e0, 0xc0217d6f4f, 0xb, 0xc003e42510, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/matrix-org/dendrite/federationapi/internal/federationclient.go:59 +0xb3
github.com/matrix-org/dendrite/keyserver/internal.(*KeyInternalAPI).queryRemoteKeysOnServer(0xc0003920a0, 0x16d2820, 0xc01ee7c270, 0xc0217d6f4f, 0xb, 0xc003e42510, 0x0, 0xc022f75a20, 0xc022f75a18, 0x2540be400, ...)
	github.com/matrix-org/dendrite/keyserver/internal/internal.go:499 +0xbfe
created by github.com/matrix-org/dendrite/keyserver/internal.(*KeyInternalAPI).queryRemoteKeys
	github.com/matrix-org/dendrite/keyserver/internal/internal.go:400 +0x4c5

goroutine 15883038 [select, 279 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc002f0b1d0)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 18891012 [select, 1 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc003e4dc20)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:263 +0x1b3
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15704470 [select, 288 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc003ee82d0)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 18891986 [select]:
net/http.(*persistConn).roundTrip(0xc001ec4d80, 0xc007e738c0, 0x0, 0x0, 0x0)
	net/http/transport.go:2610 +0x765
net/http.(*Transport).roundTrip(0xc01e176500, 0xc000d1ac00, 0xc000222878, 0x12d1901, 0xc01e9ef320)
	net/http/transport.go:592 +0xacb
net/http.(*Transport).RoundTrip(0xc01e176500, 0xc000d1ac00, 0xc, 0x16b59a0, 0xc01e176500)
	net/http/roundtrip.go:17 +0x35
github.com/matrix-org/gomatrixserverlib.(*federationTripper).RoundTrip(0xc000222870, 0xc000d1ac00, 0xc000222870, 0xc07e9102a56117b2, 0x440f83514c46)
	github.com/matrix-org/gomatrixserverlib@v0.0.0-20220224170509-f6ab9c54d052/client.go:236 +0x20e
net/http.send(0xc000d1ab00, 0x16b49c0, 0xc000222870, 0xc07e9102a56117b2, 0x440f83514c46, 0x1e50440, 0xc029320278, 0xc07e9102a56117b2, 0x1, 0x0)
	net/http/client.go:251 +0x454
net/http.(*Client).send(0xc000270980, 0xc000d1ab00, 0xc07e9102a56117b2, 0x440f83514c46, 0x1e50440, 0xc029320278, 0x0, 0x1, 0x68)
	net/http/client.go:175 +0xff
net/http.(*Client).do(0xc000270980, 0xc000d1ab00, 0x0, 0x0, 0x0)
	net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	net/http/client.go:585
github.com/matrix-org/gomatrixserverlib.(*Client).DoHTTPRequest(0xc000270980, 0x16d27e8, 0xc01fed9c80, 0xc000d1aa00, 0x56, 0xe, 0x28)
	github.com/matrix-org/gomatrixserverlib@v0.0.0-20220224170509-f6ab9c54d052/client.go:518 +0x455
github.com/matrix-org/gomatrixserverlib.(*Client).DoRequestAndParseResponse(0xc000270980, 0x16d27e8, 0xc01fed9c80, 0xc000d1aa00, 0x1295d00, 0xc017ce8228, 0x0, 0x0)
	github.com/matrix-org/gomatrixserverlib@v0.0.0-20220224170509-f6ab9c54d052/client.go:454 +0x85
github.com/matrix-org/gomatrixserverlib.(*FederationClient).doRequest(0xc000270980, 0x16d27e8, 0xc01fed9c80, 0xc002c290b0, 0x28, 0x30, 0xc002874a23, 0xc, 0x14e5583, 0x4, ...)
	github.com/matrix-org/gomatrixserverlib@v0.0.0-20220224170509-f6ab9c54d052/federationclient.go:50 +0x15d
github.com/matrix-org/gomatrixserverlib.(*FederationClient).QueryKeys(0xc000270980, 0x16d27e8, 0xc01fed9c80, 0xc002874a23, 0xc, 0xc003e42570, 0xc07e90b7a55cc219, 0x43c9a9e83eb9, 0x1e50440, 0x0, ...)
	github.com/matrix-org/gomatrixserverlib@v0.0.0-20220224170509-f6ab9c54d052/federationclient.go:456 +0x2d4
github.com/matrix-org/dendrite/federationapi/internal.(*FederationInternalAPI).QueryKeys.func1(0xc0005ac460, 0xc002874a23, 0xc, 0xc01b8ab620)
	github.com/matrix-org/dendrite/federationapi/internal/federationclient.go:60 +0x6d
github.com/matrix-org/dendrite/federationapi/internal.(*FederationInternalAPI).doRequestIfNotBackingOffOrBlacklisted(0xc0005ac460, 0xc002874a23, 0xc, 0xc004b41a10, 0x18, 0xc017ce81f8, 0x0, 0xc02462b400)
	github.com/matrix-org/dendrite/federationapi/internal/api.go:152 +0x87
github.com/matrix-org/dendrite/federationapi/internal.(*FederationInternalAPI).QueryKeys(0xc0005ac460, 0x16d27e8, 0xc01fed9c80, 0xc002874a23, 0xc, 0xc003e42570, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/matrix-org/dendrite/federationapi/internal/federationclient.go:59 +0xb3
github.com/matrix-org/dendrite/keyserver/internal.(*KeyInternalAPI).queryRemoteKeysOnServer(0xc0003920a0, 0x16d2820, 0xc01ee7c270, 0xc002874a23, 0xc, 0xc003e42570, 0x0, 0xc022f75a20, 0xc022f75a18, 0x2540be400, ...)
	github.com/matrix-org/dendrite/keyserver/internal/internal.go:499 +0xbfe
created by github.com/matrix-org/dendrite/keyserver/internal.(*KeyInternalAPI).queryRemoteKeys
	github.com/matrix-org/dendrite/keyserver/internal/internal.go:400 +0x4c5

goroutine 15563351 [select, 294 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc002f034a0)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15811708 [select, 283 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc003f725a0)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15567013 [select, 294 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc002f02690)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 18892678 [IO wait]:
internal/poll.runtime_pollWait(0x7f8ddcc0bd10, 0x77, 0xc019629b00)
	runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc003453098, 0x77, 0x16d2700, 0xc000c3e720, 0xc003453080)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitWrite(...)
	internal/poll/fd_poll_runtime.go:96
internal/poll.(*FD).WaitWrite(...)
	internal/poll/fd_unix.go:528
net.(*netFD).connect(0xc003453080, 0x16d27e8, 0xc000c3e720, 0x0, 0x0, 0x16b5e60, 0xc02002f740, 0x0, 0x0, 0x0, ...)
	net/fd_unix.go:141 +0x27b
net.(*netFD).dial(0xc003453080, 0x16d27e8, 0xc000c3e720, 0x16dac48, 0x0, 0x16dac48, 0xc012d05320, 0x0, 0x51943d, 0xc01bbc1a40)
	net/sock_posix.go:149 +0x10b
net.socket(0x16d27e8, 0xc000c3e720, 0x14e5230, 0x3, 0x2, 0x1, 0x0, 0x0, 0x16dac48, 0x0, ...)
	net/sock_posix.go:70 +0x1c5
net.internetSocket(0x16d27e8, 0xc000c3e720, 0x14e5230, 0x3, 0x16dac48, 0x0, 0x16dac48, 0xc012d05320, 0x1, 0x0, ...)
	net/ipsock_posix.go:141 +0x145
net.(*sysDialer).doDialTCP(0xc003453000, 0x16d27e8, 0xc000c3e720, 0x0, 0xc012d05320, 0x1334c00, 0x1e7fd88, 0x0)
	net/tcpsock_posix.go:65 +0xc5
net.(*sysDialer).dialTCP(0xc003453000, 0x16d27e8, 0xc000c3e720, 0x0, 0xc012d05320, 0xc013e15220, 0xc002dd1700, 0x4155fb)
	net/tcpsock_posix.go:61 +0xd7
net.(*sysDialer).dialSingle(0xc003453000, 0x16d27e8, 0xc000c3e720, 0x16c5850, 0xc012d05320, 0x0, 0x0, 0x0, 0x0)
	net/dial.go:580 +0x5e8
net.(*sysDialer).dialSerial(0xc003453000, 0x16d27e8, 0xc000c3e720, 0xc020f93550, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	net/dial.go:548 +0x15e
net.(*Dialer).DialContext(0x1de6040, 0x16d27e8, 0xc000c3e720, 0x14e5230, 0x3, 0xc013e15220, 0x10, 0x0, 0x0, 0x0, ...)
	net/dial.go:425 +0x6e5
net/http.(*Transport).dial(0xc029618b40, 0x16d2820, 0xc01d8425d0, 0x14e5230, 0x3, 0xc013e15220, 0x10, 0x0, 0x10, 0x10, ...)
	net/http/transport.go:1162 +0x1ff
net/http.(*Transport).dialConn(0xc029618b40, 0x16d2820, 0xc01d8425d0, 0x0, 0x14e6988, 0x5, 0xc013e15220, 0x10, 0x0, 0xc001ec58c0, ...)
	net/http/transport.go:1600 +0x1b85
net/http.(*Transport).dialConnFor(0xc029618b40, 0xc0015f3130)
	net/http/transport.go:1442 +0xc6
created by net/http.(*Transport).queueForDial
	net/http/transport.go:1411 +0x40f

goroutine 15978686 [select, 274 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc003c0f1d0)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 16360198 [select, 239 minutes]:
github.com/matrix-org/dendrite/federationapi/statistics.(*ServerStatistics).Failure.func1(0xc02f340c60)
	github.com/matrix-org/dendrite/federationapi/statistics/statistics.go:130 +0xff
created by github.com/matrix-org/dendrite/federationapi/statistics.(*ServerStatistics).Failure
	github.com/matrix-org/dendrite/federationapi/statistics/statistics.go:127 +0x1cc

goroutine 15660954 [select, 290 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc00330bb30)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15803409 [select, 283 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc00292af00)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15673975 [select, 289 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc001d8c960)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15673406 [select, 289 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc006fe64b0)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15673886 [select, 289 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc003ee83c0)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15702632 [select, 288 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc006e8d0e0)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15653504 [select, 290 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc00473ca50)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 18891894 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f8ddd1c60c8, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc001d34798, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc001d34780, 0xc01bbc17b1, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc001d34780, 0xc01bbc17b1, 0x1, 0x1, 0xc001978fa8, 0x7817f4, 0xc0028da180)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc02010ff38, 0xc01bbc17b1, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xc01bbc17a0)
	net/http/server.go:672 +0x58
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:668 +0xd5

goroutine 15865037 [select, 280 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc004fbe0f0)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15846017 [select, 281 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc0015da000)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 18892129 [select]:
net/http.(*persistConn).writeLoop(0xc001ec4d80)
	net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	net/http/transport.go:1744 +0xc9c

goroutine 17798634 [select, 91 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc0027061e0)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15803282 [select, 283 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc0031fb770)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15268464 [select, 313 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc006223c20)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 16828863 [select, 200 minutes]:
github.com/matrix-org/dendrite/federationapi/statistics.(*ServerStatistics).Failure.func1(0xc02efa8960)
	github.com/matrix-org/dendrite/federationapi/statistics/statistics.go:130 +0xff
created by github.com/matrix-org/dendrite/federationapi/statistics.(*ServerStatistics).Failure
	github.com/matrix-org/dendrite/federationapi/statistics/statistics.go:127 +0x1cc

goroutine 18891987 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc022f75a28)
	runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc022f75a20)
	sync/waitgroup.go:130 +0x65
github.com/matrix-org/dendrite/keyserver/internal.(*KeyInternalAPI).queryRemoteKeys.func1(0xc022f75a20, 0xc0263290e0)
	github.com/matrix-org/dendrite/keyserver/internal/internal.go:408 +0x2b
created by github.com/matrix-org/dendrite/keyserver/internal.(*KeyInternalAPI).queryRemoteKeys
	github.com/matrix-org/dendrite/keyserver/internal/internal.go:407 +0x51b

goroutine 15804178 [select, 283 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc0022bde00)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15842081 [select, 281 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc00292bd10)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15253677 [select, 314 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc001d8ca50)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 16591107 [select, 221 minutes]:
github.com/matrix-org/dendrite/federationapi/statistics.(*ServerStatistics).Failure.func1(0xc02f341980)
	github.com/matrix-org/dendrite/federationapi/statistics/statistics.go:130 +0xff
created by github.com/matrix-org/dendrite/federationapi/statistics.(*ServerStatistics).Failure
	github.com/matrix-org/dendrite/federationapi/statistics/statistics.go:127 +0x1cc

goroutine 15559957 [select, 294 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc002a46c30)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15973874 [select, 275 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc00509db30)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:168 +0x66

goroutine 15793202 [select, 284 minutes]:
github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).backgroundSend(0xc006ed5d10)
	github.com/matrix-org/dendrite/federationapi/queue/destinationqueue.go:303 +0x730
created by github.com/matrix-org/dendrite/federationapi/queue.(*destinationQueue).wakeQueueIfNeeded
	
```

**Comment by kegsay** [comment]
I don't see any panics in this goroutine dump?

**Comment by catsmeows** [comment]
I dont have additional logs
