### ISSUE TITLE
configuration requests ack wait to be 2m10s, but consumer's value is 30s

### ISSUE THREAD

**Issue by BratishkaErik** [matrix-org/dendrite#2286]
### Background information
- **Dendrite version or git SHA**: e47dfe47865b3d4f3a086325d01f5c8d69f2b23f
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres 14.2
- **Running in Docker?**: No
- **`go version`**: go version go1.18 linux/amd64
- **Client used (if applicable)**: Not applicable

### Description

 - **What** is the problem: Crash on startup 
 - **Who** is affected: Server admin
 - **How** is this bug manifesting: 
```
INFO[2022-03-19T13:07:42.692532591Z] Enabled perspective key fetcher               num_public_keys=2 server_name=matrix.org
PANI[2022-03-19T13:07:42.703391313Z] failed to start roomserver input API          error="configuration requests ack wait to be 2m10s, but consumer's value is 30s"
panic: (*logrus.Entry) 0xc000187030

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc000186fc0, 0x0, {0xc0000ef1a0, 0x24})
        github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x43e
github.com/sirupsen/logrus.(*Entry).Log(0xc000186fc0, 0x0, {0xc0005ab910?, 0xc0005ab970?, 0x45f209?})
        github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
        github.com/sirupsen/logrus@v1.8.1/entry.go:331
github.com/MFAshby/stdemuxerhook.(*StdDemuxerHook).Fire(0x0?, 0xc000186ee0)
        github.com/MFAshby/stdemuxerhook@v1.0.0/stdemuxerhook.go:58 +0x19e
github.com/sirupsen/logrus.LevelHooks.Fire(0xc0005aba50?, 0x5aba20?, 0x4?)
        github.com/sirupsen/logrus@v1.8.1/hooks.go:28 +0x82
github.com/sirupsen/logrus.(*Entry).fireHooks(0xc000186ee0)
        github.com/sirupsen/logrus@v1.8.1/entry.go:272 +0x1dc
github.com/sirupsen/logrus.(*Entry).log(0xc000186e70, 0x0, {0xc0000ef140, 0x24})
        github.com/sirupsen/logrus@v1.8.1/entry.go:241 +0x34f
github.com/sirupsen/logrus.(*Entry).Log(0xc000186e70, 0x0, {0xc0005abd08?, 0x11988a0?, 0xc000527900?})
        github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
        github.com/sirupsen/logrus@v1.8.1/entry.go:331
github.com/matrix-org/dendrite/roomserver/internal.(*RoomserverInternalAPI).SetFederationAPI(0xc0002d12c0, {0x1563af8?, 0xc0004f4460}, 0xc000344450)
        github.com/matrix-org/dendrite/roomserver/internal/api.go:163 +0x8ea
main.main()
        github.com/matrix-org/dendrite/cmd/dendrite-monolith-server/main.go:134 +0x86a
```
 - **When** did this first appear: IDK

### Steps to reproduce

- Not reproducible (With clean database and same config)

**Comment by BratishkaErik** [comment]
Tested 98a5e410d7ecae49f525ddabc55a86d8a6731f22, problem dissapeared. Thank you very much!
