### ISSUE TITLE
crash on send a log message logrus

### ISSUE THREAD

**Issue by genofire** [matrix-org/dendrite#2414]
### Background information

- **Dendrite version or git SHA**: 0.8.2.r17.gbfa344e83-1
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgresql
- **Running in Docker?**: no
- **`go version`**: go version go1.18 linux/amd64
- **Client used (if applicable)**:

### Description

 - **What** is the problem:
 - **Who** is affected:
 - **How** is this bug manifesting:
 - **When** did this first appear: request verification from an synanpse server per emoji

```
May 04 12:45:42 vela-www dendrite[317932]: time="2022-05-04T10:45:42.592701427Z" level=error msg="Failed to clean EDUs for server \"schaffarzik.net\"" error="sqlutil.WithTransaction.Begin: pq: sorry, too many clients already"
May 04 12:45:42 vela-www dendrite[317932]: time="2022-05-04T10:45:42.594090438Z" level=error msg="Failed to get pending PDUs for \"gottliebtfreitag.de\"" error="sqlutil.WithTransaction.Begin: pq: remaining connection slots are reserved for non-replication superuser connections"
May 04 12:45:42 vela-www dendrite[317932]: time="2022-05-04T10:45:42.596201994Z" level=error msg="Failed to clean EDUs for server \"abolivier.bzh\"" error="sqlutil.WithTransaction.Begin: pq: remaining connection slots are reserved for non-replication superuser connections"May 04 12:45:42 vela-www dendrite[317932]: time="2022-05-04T10:45:42.599063771Z" level=error msg="Failed to clean EDUs for server \"dou10s.com\"" error="sqlutil.WithTransaction.Begin: pq: remaining connection slots are reserved for non-replication superuser connections"
May 04 12:45:42 vela-www dendrite[317932]: panic: (*logrus.Entry) 0xc00682db90
May 04 12:45:42 vela-www dendrite[317932]: goroutine 19406 [running]:
May 04 12:45:42 vela-www dendrite[317932]: github.com/sirupsen/logrus.(*Entry).log(0xc00682db20, 0x0, {0xc0025e3f00, 0x1b})
May 04 12:45:42 vela-www dendrite[317932]:         github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x43e
May 04 12:45:42 vela-www dendrite[317932]: github.com/sirupsen/logrus.(*Entry).Log(0xc00682db20, 0x0, {0xc005f82f18?, 0xc005f82f78?, 0x5557f1b32ec9?})
May 04 12:45:42 vela-www dendrite[317932]:         github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
May 04 12:45:42 vela-www dendrite[317932]: github.com/sirupsen/logrus.(*Entry).Panic(...)
May 04 12:45:42 vela-www dendrite[317932]:         github.com/sirupsen/logrus@v1.8.1/entry.go:331
May 04 12:45:42 vela-www dendrite[317932]: github.com/MFAshby/stdemuxerhook.(*StdDemuxerHook).Fire(0x0?, 0xc00682dab0)
May 04 12:45:42 vela-www dendrite[317932]:         github.com/MFAshby/stdemuxerhook@v1.0.0/stdemuxerhook.go:58 +0x19e
May 04 12:45:42 vela-www dendrite[317932]: github.com/sirupsen/logrus.LevelHooks.Fire(0xc005f83058?, 0x5f83028?, 0x555700000000?)
May 04 12:45:42 vela-www dendrite[317932]:         github.com/sirupsen/logrus@v1.8.1/hooks.go:28 +0x82
May 04 12:45:42 vela-www dendrite[317932]: github.com/sirupsen/logrus.(*Entry).fireHooks(0xc00682dab0)
May 04 12:45:42 vela-www dendrite[317932]:         github.com/sirupsen/logrus@v1.8.1/entry.go:272 +0x1dc
May 04 12:45:42 vela-www dendrite[317932]: github.com/sirupsen/logrus.(*Entry).log(0xc00682da40, 0x0, {0xc0025e3ec0, 0x1b})
May 04 12:45:42 vela-www dendrite[317932]:         github.com/sirupsen/logrus@v1.8.1/entry.go:241 +0x34f
May 04 12:45:42 vela-www dendrite[317932]: github.com/sirupsen/logrus.(*Entry).Log(0xc00682da40, 0x0, {0xc005f832f8?, 0x0?, 0x0?})
May 04 12:45:42 vela-www dendrite[317932]:         github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
May 04 12:45:42 vela-www dendrite[317932]: github.com/sirupsen/logrus.(*Entry).Logf(0xc00682da40, 0x0, {0x5557f27f229b?, 0x5?}, {0x0?, 0xc0025e34c0?, 0x1f?})
May 04 12:45:42 vela-www dendrite[317932]:         github.com/sirupsen/logrus@v1.8.1/entry.go:338 +0x85
May 04 12:45:42 vela-www dendrite[317932]: github.com/sirupsen/logrus.(*Entry).Panicf(...)
May 04 12:45:42 vela-www dendrite[317932]:         github.com/sirupsen/logrus@v1.8.1/entry.go:376
```

**Comment by neilalexander** [comment]
I suspect there is more to this log trace than is visible. Are your log lines clipped?

**Comment by genofire** [comment]
i keep for panic:
```
journalctl --since -2h -u dendrite | grep panic
May 04 17:14:48 vela-www dendrite[321859]: time="2022-05-04T15:14:48.244203187Z" level=error msg="Failed to clean EDUs for server \"kernelpanic.cafe\"" error="sqlutil.WithTransaction.Begin: pq: remaining connection slots are reserved for non-replication superuser connections"
May 04 17:14:48 vela-www dendrite[321859]: time="2022-05-04T15:14:48.258046563Z" level=error msg="Failed to remove \"kernelpanic.cafe\" from blacklist" error="sqlutil.WithTransaction.Begin: pq: remaining connection slots are reserved for non-replication superuser connections"
May 04 17:26:39 vela-www dendrite[321859]: time="2022-05-04T15:26:39.597617302Z" level=error msg="Failed to get pending PDUs for \"kernelpanic.cafe\"" error="sqlutil.WithTransaction.Begin: pq: remaining connection slots are reserved for non-replication superuser connections"
May 04 18:37:20 vela-www dendrite[321859]: time="2022-05-04T16:37:20.785920487Z" level=panic msg="could not save account data" error="pq: remaining connection slots are reserved for non-replication superuser connections" room_id="" type=im.vector.setting.breadcrumbs
May 04 18:37:20 vela-www dendrite[321859]: panic: (*logrus.Entry) 0xc0002d8d90
May 04 18:37:50 vela-www dendrite[324862]: time="2022-05-04T16:37:50.030038588Z" level=panic msg="could not save account data" error="pq: remaining connection slots are reserved for non-replication superuser connections" room_id="" type=im.vector.setting.breadcrumbs
May 04 18:37:50 vela-www dendrite[324862]: panic: (*logrus.Entry) 0xc0099d92d0
May 04 18:38:13 vela-www dendrite[324939]: time="2022-05-04T16:38:13.929454396Z" level=panic msg="could not save account data" error="pq: remaining connection slots are reserved for non-replication superuser connections" room_id="!KqkRjyTEzAGRiZFBYT:nixos.org" type=m.fully_read
May 04 18:38:13 vela-www dendrite[324939]: panic: (*logrus.Entry) 0xc00e2e31f0
May 04 18:38:46 vela-www dendrite[324976]: time="2022-05-04T16:38:46.377328557Z" level=error msg="failed to associate EDU with destination \"kernelpanic.cafe\"" error="sqlutil.WithTransaction.Begin: pq: remaining connection slots are reserved for non-replication superuser connections"
May 04 18:40:18 vela-www dendrite[324976]: time="2022-05-04T16:40:18.705710548Z" level=panic msg="could not save account data" error="pq: remaining connection slots are reserved for non-replication superuser connections" room_id="!KqkRjyTEzAGRiZFBYT:nixos.org" type=m.fully_read
May 04 18:40:18 vela-www dendrite[324976]: panic: (*logrus.Entry) 0xc0017f4f50
May 04 18:50:48 vela-www dendrite[325054]: time="2022-05-04T16:50:48.105657419Z" level=error msg="Failed to get pending PDUs for \"kernelpanic.cafe\"" error="sqlutil.WithTransaction.Begin: pq: remaining connection slots are reserved for non-replication superuser connections"
```

**Comment by neilalexander** [comment]
It looks like you've configured more PostgreSQL connections in your Dendrite config than PostgreSQL is configured to allow?

**Comment by genofire** [comment]
i ingress the count already -> looks current okay
