### ISSUE TITLE
Crash after calling DendriteMonolith.stop()

### ISSUE THREAD

**Issue by Juha-Park-TII** [matrix-org/dendrite#2520]
### Background information

- **Dendrite version or git SHA**: 0.8.7
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: No Idea
- **Running in Docker?**: No
- **`go version`**: go1.17.7 darwin/amd64
- **Client used (if applicable)**: 

### Description

 - **What** is the problem: When Dendrite monolith in android stop, it crashes
 - **Who** is affected: Dendrite in Android
 - **How** is this bug manifesting: E/GoLog: time="2022-06-07T08:59:02.988851880Z" level=fatal msg="accept tcp 127.0.0.1:65432: use of closed network connection"
 - **When** did this first appear: it happens all the time regardless of dendrite version when dendrite server is stopped

### Steps to reproduce

- list the steps
   1. monolith = DendriteMonolith()
   2. monolith ?.storageDirectory = applicationContext.filesDir.toString()
   3. monolith ?.cacheDirectory = applicationContext.cacheDir.toString()
   4. monolith ?.start()
   5. monolith?.stop()
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
Is this `dendrite-demo-pinecone` or `dendrite-demo-yggdrasil`?

**Comment by Juha-Park-TII** [comment]
dendrite-demo-pinecone

**Comment by neilalexander** [comment]
Can you please see if commit `aafb7bf12` is better?

**Comment by neilalexander** [comment]
What is the panic / exception output?

**Comment by Juha-Park-TII** [comment]
No message for panic or exception. APK is just closed

**Comment by Juha-Park-TII** [comment]
If you just start and stop in android, you can see the problem. if it is not, then maybe there is something wrong in using dendrite in android.

**Comment by Juha-Park-TII** [comment]
E/Go: panic: listen tcp 127.0.0.1:65432: bind: address already in use
E/Go: goroutine 17 [running, locked to thread]:
E/GoLog: panic: listen tcp 127.0.0.1:65432: bind: address already in use
E/Go: github.com/matrix-org/dendrite/build/gobind-pinecone.(*DendriteMonolith).Start(0x4000b24540)
E/Go: github.com/matrix-org/dendrite@v0.0.0-00010101000000-000000000000/build/gobind-pinecone/monolith.go:230 +0x1ce8
E/Go: main.proxygobind_DendriteMonolith_Start(0xffffffe7)
E/Go: 	gobind/gobind/go_gobindmain.go:269 +0x54
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 1792 (p.matrix_server), pid 1792 (p.matrix_server)

**Comment by jestun-snp** [comment]
Please ignore this log. It is not printing error or panic log and crash

> E/Go: panic: listen tcp 127.0.0.1:65432: bind: address already in use E/Go: goroutine 17 [running, locked to thread]: E/GoLog: panic: listen tcp 127.0.0.1:65432: bind: address already in use E/Go: github.com/matrix-org/dendrite/build/gobind-pinecone.(*DendriteMonolith).Start(0x4000b24540) E/Go: github.com/matrix-org/dendrite@v0.0.0-00010101000000-000000000000/build/gobind-pinecone/monolith.go:230 +0x1ce8 E/Go: main.proxygobind_DendriteMonolith_Start(0xffffffe7) E/Go: gobind/gobind/go_gobindmain.go:269 +0x54 A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 1792 (p.matrix_server), pid 1792 (p.matrix_server)
