### ISSUE TITLE
Dendrite panic on syncapi jetstream

### ISSUE THREAD

**Issue by hdhog** [matrix-org/dendrite#2798]
### Background information

- **Dendrite version or git SHA**: 0.10.3
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: PostgreSQL
- **Running in Docker?**: yes
- **Client used (if applicable)**: server side

### Description

- **What** is the problem: panic on roomeventconsumer and restart
- **Who** is affected: all users
- **How** is this bug manifesting: server restarted
- **When** did this first appear:

last log
```
time="2022-10-16T05:36:09.361354944Z" level=error msg="Failed to acquire database snapshot for sync request" error="context canceled"
time="2022-10-16T05:36:09.361394483Z" level=error msg="Failed to acquire database snapshot for sync request" error="context canceled"
time="2022-10-16T05:36:09.360830889Z" level=error msg="GetEvent: syncDB.NewDatabaseTransaction failed" error="context canceled" event_id="$F79b7RslJn_KLnQYvq2nMH5IoInKsmi-xUimRdlijME" req.id=baXQgUAzTNUS req.method=GET req.path="/_matrix/client/v3/rooms/!KqkRjyTEzAGRiZFBYT:nixos.org/event/$F79b7RslJn_KLnQYvq2nMH5IoInKsmi-xUimRdlijME" room_id="!KqkRjyTEzAGRiZFBYT:nixos.org" user_id="@hdhog:matrix.hdhog.ru"
time="2022-10-16T05:36:11.769729776Z" level=panic msg="roomserver output log: write new event failure" add="[$YS2FFKq3PfAbm5rZsVapvQQaUOKtfs_zcKmVOIUfGlY $5is-LYQo2L0Haoh4wJ67EKsVFftU3NHqO0Z_LGUVor0 $TrcRT6hmenmTx4sXFlQdyrJPUs7j-P-G14Ta-9nXgWs $hhr7lAN-45ZVm5pOyT811j7PRBSzlVlzwI1RGFXALXM $niefVlQsLWPCmAif7xcq_B2_3VSVxvPslwuEI_H3i2o $PchbUq4ZMRxlwRJ5swdEfKAJ_82qv6cWqxLOO1xojt8 $BrrQ-dZEjblxISqA5A2p5xeY6dyeCGM0dhzahnBfc3c $U4wLJalKSW4121plydlljXuQIuGQbajJixEjTJ434CA $xOtP2LpV1G6M_oNeTTIGZRm7MDSr0iazC_lkB4kcPaQ $zvvoRHW6au4L0ULlR-h9ab91dew8mEBNwqh-kNNhiAw $G8uY3lglKCJ8pYuKiQnSb8vIKmQcDFWnInrKcs14jJw $NJl3afzuiDMrdFQQeMF2MfpO0TEUHyAUwHOxTkUwSgs $jC49UmRBEiK6eINbjZTOuK6SkdjylTEe8wL5oJaMDTc $iCP64E_d2vEiyVibAayhV02JkgXEGExZqkAEQS8PeIY $-_iX7bsQXPwB5295idBk_mHTyGtckPTeXv3kmtFUs4A $htYw1h5eSQnAyeLCX5iEvD3g8py_onUuDDtAoOcAixQ $LcGmh_WuLiRemXtxfUPmLA72PR_glrToClYcbvrOQ2A $VzR6JVw7rBOUQLKlEC5JPNDGID_B4urhFnJKnMaeurE $pzx2HKdHiKCqxoEt9R5GpiYDAHrllHE579c8OhHUKZ4 $7i5cEV5x7nZPTv441QqxKY4r-lSSnA443Hoh6lRhJdc $KjRNcuHTMcJ4XakXUEji2d9Ub6PTmD5-m2u7MCcQDXk $IZop0HSKRmJfVxbZnWzrftIHA-Y9u4YeWWscr03_3EE 
*********** remove many lines ***************
$Ufq4UZ6ladgf1FqA7XVZfwBbizdhH-0Xx_ybCEBygw8 $45OF-eEYm2WWXGH3wGxz49rtVdgT1Vd-k8nxenxYA00 $p1Ci-g2ZziSjtc_Slkr5T8G49H-DTwoH3QmYSXuc1pc $ro1kl07V4kGvchP46CKuy2MRqXZT8gOG6m8u5NanTPg $jVDY1ylN7vKKRB5nHTsqQH75ciiUUUcP8F2zGyOi1r8 $m7P9jSYBAjTJYPucNSB4riJDqHH-se8qGRt870vcY_I $UxQJR2PBUr4DFe-LGio_t-YKM_rhjEWYsWBV-iP2hp8 $xykKCbew2hPcsCrQ5U17BmqphKibuem2E3N1zUGou8o $U9ty-KAq3LoWItQsneBK-cKU-O_5DUYlj8VSWE22uLw $4UYWA-gkeH6Nw__q31YetLNrqabrDOourz2wF2D_LoU $bwfQxLXwtVOzcIVqFg3C699ilRmwsCXbml97tdqnJ0A $1sbPWaxLoIyvSNze_-HTezevxzqpEMeJXqJs-cBBmKo $fyKPjuYFD9kJa5AuNCxKJU2w6jdfkDZGrNOW5Flfxu0 $PvHT3jwSVyYZarPkS8htCu8VO-9p72NHz9Vhi0XNdf4 $3VSXkMquI3Qws-OZp-EQQtCpYnHD4Z7dRDfbDH314FI $iNKlqw5Mgr7VVztgeyVfFtlzuKSHgUxHiOxqdbQv3i8 $3-JzdCPmygNacTss0Z3OCWqOqm4tsXq02ogeIaJ0z7o $K_f6OzBIMU7fZ6492-XlBxU2MbCV7_Bmo4fcM25WIdc $TZTzwyJLsBYLJtXPGUx2XLix_K99cWZUXOI-ljPk_cE $DrR6RaYk_eNKET4ZclFakjLAYQobEYUwKw7TRmHyXWk $HmDvRbETeGpn_ka7pv-ie7f6k5mKPBh1lGBT7DQWTAg $ZhQQgvz-W62kHSivJq1tntxK8RVJuudjS8MkQEMvxt0 $TnspHK9FpkAzuejtC7jGC27kQnl_X_XTGNvLJLQAFjY $KECPPOz-DNEDcKYPp7SFHXcJd8JpER9XJXI6NpTOcpI $H-PzC1Y6NtzOcTl-B55e9WFuMDkEnmj_sYyXFKpT7l4 $8-rjdtvxaTSEtKp3hyPPx3nWhitpb-qVB3uWBJO8skg $2ZsBe-u4Ijzl4yjLpM7VZX7LV-jEtG6HIpzOvNuyAYE $HO6LKWASWzvdX5b50H82hEmS-l8KRFjV2EJdXT8qpyA $iASnZDDA2HVU8JbYFIWT3bV8mZBNejEXh34bswkSqkI $lxIaVm2WPtvM6jJlLz2rPesFORyOz8XRgsoYeZ5oQow $3IiZmItu-8Vc3vqAImVcVeNLhEtrSrXiVyEwbI13FoU $JPSPp9_vXyvsFc77fHe6uB7OsTvR-iA98cza7w81iCQ $mc84WsQXmUO3mvARUMYeyBVSNZctxlduxElRWBFa5ps $U-HLCH4oORY3kjBNyPSKdcfPXELSaoTKo5Uv6VyfGQM $d6tto_Nc0lfJu61pdq7CqUMK6nU41k42pGVM2-UGwLA $LvTDk6mzTVw3556vkIZ1O294pcf0twiv3xo1wME9_6U $vtK04MbnO5ac3Z31Fk60DYSQH6wu2Ywfn-qF1YC7mtw $eSBJNfIRjqhKjhzaP6iEDMMT2hDq58E_KS7Icm_Kfq0 $Jllq1-gajPNu1H8tdPb67Zzmu2Ct8XrPdZ7FNWX8UMo $e7a6dH_yLunuKyOk_ca4Bw9gcCTz8zw1eLCP6N3359w $vlY4XIoZfHd0pVibJVrqHmPFJJoFEQjeD5r3OYN1NsY $87K12_1jJwL3YhjwfiUTsZB6ZNl4I8g7mnIXTUY8iQ4 $4L5FbL3JObcNs_8AxTfQdXpqpqsEKevyBKSJQNAl5_g $BH0zYB2Uy9vUif72qMnXRv1tiw1RGlI7A_dtSDkCthw $IYHMO4WxDsHiEwCI2RG7KiuWgtTSGmn-pzJVtcNS75w $XB8ODTGqmWue_kzaCwfZDarPETS69-P131GoLy7Yj4w $pFcpGUMoshGN5VnJSXa98WOUaFyGVWgncN16V3d1hok $TOfKRr4kXU8-siQfvcUurfALzyJZMACftTckIq7I5YI $HdwRGEaz5rYmEdc7aR1gazoGRU-ockfmJcvRVyFweIo]" del="[]" error="d.Memberships.UpsertMembership: pq: duplicate key value violates unique constraint \"syncapi_memberships_unique\"" event="{\"auth_events\":[\"$YS2FFKq3PfAbm5rZsVapvQQaUOKtfs_zcKmVOIUfGlY\",\"$LKsl93OKRQ-_S9qJcDcZZB4vpBQ9EQXRjt1HbohkYVE\",\"$TrcRT6hmenmTx4sXFlQdyrJPUs7j-P-G14Ta-9nXgWs\",\"$5is-LYQo2L0Haoh4wJ67EKsVFftU3NHqO0Z_LGUVor0\"],\"content\":{\"avatar_url\":\"mxc://lassul.us/mSBytdnmcCoAFjWHVslfgOJw\",\"displayname\":\"lassulus\",\"membership\":\"invite\"},\"depth\":7147,\"hashes\":{\"sha256\":\"VPR4Nz1glRDZNzyqxHY675lIJuPAHb8pS1J/IaVO4eQ\"},\"origin\":\"nixos.dev\",\"origin_server_ts\":1665833783154,\"prev_events\":[\"$bwfQxLXwtVOzcIVqFg3C699ilRmwsCXbml97tdqnJ0A\",\"$Hwf9cce64pn0EgrXWEuAgFRKlCw5NPKIxCkxrwyOrMw\"],\"room_id\":\"!MKvhXlSTLGJUXpYuWF:nixos.org\",\"sender\":\"@lassulus:nixos.dev\",\"signatures\":{\"lassul.us\":{\"ed25519:a_MvbO\":\"d0fWw/wLDVxlEUQsxCP/ecgchdlfsy0JpXqIhhBuiOccHg+OqYA8qRgZIAJWTcGvppj0tJlzOFNOIpY7IDfRBg\"},\"nixos.dev\":{\"ed25519:a_NQWV\":\"QRcTd1lrgb/xITfHoHTL1PdWb2J4fYz/qeHEA/FEig9rCJYY0qT9VyMz2C0AwNR+x03OXbviYqaP1vMoi/bHCg\"}},\"state_key\":\"@lassulus:lassul.us\",\"type\":\"m.room.member\"}" event_id="$_HgVf2QlLSWPB8OC49jFsGihPqb3o-Q7IV6Kz3ln9Pg"
panic: (*logrus.Entry) 0xc011f04070

goroutine 405 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc011f04000, 0x0, {0xc00b9140f0, 0x2e})
	github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4a7
github.com/sirupsen/logrus.(*Entry).Log(0xc011f04000, 0x0, {0xc011eda898?, 0xc011eda8f8?, 0x0?})
	github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
	github.com/sirupsen/logrus@v1.9.0/entry.go:342
github.com/MFAshby/stdemuxerhook.(*StdDemuxerHook).Fire(0x0?, 0xc006ac3f80)
	github.com/MFAshby/stdemuxerhook@v1.0.0/stdemuxerhook.go:58 +0x19e
github.com/sirupsen/logrus.LevelHooks.Fire(0xc011eda9d8?, 0x11eda9a8?, 0x4?)
	github.com/sirupsen/logrus@v1.9.0/hooks.go:28 +0x82
github.com/sirupsen/logrus.(*Entry).fireHooks(0xc006ac3f80)
	github.com/sirupsen/logrus@v1.9.0/entry.go:280 +0x1dc
github.com/sirupsen/logrus.(*Entry).log(0xc006ac3f10, 0x0, {0xc00b9140c0, 0x2e})
	github.com/sirupsen/logrus@v1.9.0/entry.go:242 +0x390
github.com/sirupsen/logrus.(*Entry).Log(0xc006ac3f10, 0x0, {0xc011edac98?, 0x0?, 0x0?})
	github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Logf(0xc006ac3f10, 0x0, {0x187ec27?, 0x3?}, {0x0?, 0x0?, 0xc012d105c0?})
	github.com/sirupsen/logrus@v1.9.0/entry.go:349 +0x85
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	github.com/sirupsen/logrus@v1.9.0/entry.go:387
github.com/matrix-org/dendrite/syncapi/consumers.(*OutputRoomEventConsumer).onNewRoomEvent(0xc0041e7b80, {0x1ad6ef0, 0xc0043b2720}, {0xc018f0b590, 0x1, {0xc00bd3f580, 0x1, 0x4}, {0xc016772000, 0xecf, ...}, ...})
	github.com/matrix-org/dendrite/syncapi/consumers/roomserver.go:268 +0xd55
github.com/matrix-org/dendrite/syncapi/consumers.(*OutputRoomEventConsumer).onMessage(0xc0041e7b80, {0xc015bf9de0?, 0xc00f4139c0?}, {0xc012d1a4e8?, 0xc00f4139c0?, 0xc00fd97a60?})
	github.com/matrix-org/dendrite/syncapi/consumers/roomserver.go:117 +0x3f8
github.com/matrix-org/dendrite/setup/jetstream.JetStreamConsumer.func2()
	github.com/matrix-org/dendrite/setup/jetstream/helpers.go:91 +0x71e
created by github.com/matrix-org/dendrite/setup/jetstream.JetStreamConsumer
	github.com/matrix-org/dendrite/setup/jetstream/helpers.go:43 +0x31e

```

**Comment by S7evinK** [comment]
Error extracted:
```
error="d.Memberships.UpsertMembership: pq: duplicate key value violates unique constraint \"syncapi_memberships_unique\""
```

The tests added in #2805 can't reproduce this.

**Comment by imyxh** [comment]
I have either the same issue or a similar one:

```
dendrite[154177]: time="2024-01-28T06:45:46.970491319Z" level=panic msg="roomserver output log: write new event failure" add="[...]" del="[...]" error="d.CurrentRoomState.UpsertRoomState: pq: duplicate key value violates unique constraint \"syncapi_current_room_state_eventid_idx\"" event="{\"auth_events\":[...],\"content\":{\"membership\":\"leave\"},...}"
dendrite[154177]: panic: (*logrus.Entry) 0xc002e7b570
dendrite[154177]: goroutine 415 [running]:
dendrite[154177]: github.com/sirupsen/logrus.(*Entry).log(0xc002e7b490, 0x0, {0xc0082b86c0, 0x2e})
dendrite[154177]:         github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
dendrite[154177]: github.com/sirupsen/logrus.(*Entry).Log(0xc002e7b490, 0x0, {0xc009d92288?, 0x651b3def52bc?, 0x0?})
dendrite[154177]:         github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
dendrite[154177]: github.com/sirupsen/logrus.(*Entry).Panic(...)
dendrite[154177]:         github.com/sirupsen/logrus@v1.9.3/entry.go:342
dendrite[154177]: github.com/MFAshby/stdemuxerhook.(*StdDemuxerHook).Fire(0x0?, 0xc002e7b420)
dendrite[154177]:         github.com/MFAshby/stdemuxerhook@v1.0.0/stdemuxerhook.go:58 +0x198
dendrite[154177]: github.com/sirupsen/logrus.LevelHooks.Fire(0xc009d923c8?, 0x9d92398?, 0x651b00000004?)
dendrite[154177]:         github.com/sirupsen/logrus@v1.9.3/hooks.go:28 +0x70
dendrite[154177]: github.com/sirupsen/logrus.(*Entry).fireHooks(0xc002e7b420)
dendrite[154177]:         github.com/sirupsen/logrus@v1.9.3/entry.go:280 +0x1fa
dendrite[154177]: github.com/sirupsen/logrus.(*Entry).log(0xc002e7b2d0, 0x0, {0xc0082b8690, 0x2e})
dendrite[154177]:         github.com/sirupsen/logrus@v1.9.3/entry.go:242 +0x399
dendrite[154177]: github.com/sirupsen/logrus.(*Entry).Log(0xc002e7b2d0, 0x0, {0xc009d92678?, 0x0?, 0x0?})
dendrite[154177]:         github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
dendrite[154177]: github.com/sirupsen/logrus.(*Entry).Logf(0xc002e7b2d0, 0x0, {0x651b3e08ae07?, 0x3?}, {0x0?, 0x80?, 0xc00446fda0?})
dendrite[154177]:         github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0x7c
dendrite[154177]: github.com/sirupsen/logrus.(*Entry).Panicf(...)
dendrite[154177]:         github.com/sirupsen/logrus@v1.9.3/entry.go:387
dendrite[154177]: github.com/matrix-org/dendrite/syncapi/consumers.(*OutputRoomEventConsumer).onNewRoomEvent(0xc0000cd290, {0x651b3e6b12d0, 0xc0003b6f90}, {0xc00421f620, 0x0, {0xc031d5a600, 0x2, 0x2}, {0xc00392d800, 0x47, ...}, ...})
dendrite[154177]:         github.com/matrix-org/dendrite/syncapi/consumers/roomserver.go:290 +0x1038
dendrite[154177]: github.com/matrix-org/dendrite/syncapi/consumers.(*OutputRoomEventConsumer).onMessage(0xc0000cd290, {0xc031d5a3e0?, 0x651b3e625100?}, {0xc009e68d48?, 0xc002ddd600?, 0xc0054f5a10?})
dendrite[154177]:         github.com/matrix-org/dendrite/syncapi/consumers/roomserver.go:125 +0x618
dendrite[154177]: github.com/matrix-org/dendrite/setup/jetstream.JetStreamConsumer.func2()
dendrite[154177]:         github.com/matrix-org/dendrite/setup/jetstream/helpers.go:100 +0x454
dendrite[154177]: created by github.com/matrix-org/dendrite/setup/jetstream.JetStreamConsumer in goroutine 1
dendrite[154177]:         github.com/matrix-org/dendrite/setup/jetstream/helpers.go:44 +0x305
systemd[1]: dendrite.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

This one seems to happen mostly in UpsertRoomState. I have to wipe the jetstream directory and restart to get the server working, and then after a few minutes it'll happen again.

**Comment by niebloomj** [comment]
Has anyone been successful with any workaround?

**Comment by alistair23** [comment]
Same issue here

```
Oct 09 04:36:25 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:36:25.680217944Z" level=info msg="User requested to room join" room_id="#remarkable:matrix.org" ser>
Oct 09 04:36:36 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:36:36.242609247Z" level=info msg="Signalling other goroutines waiting for this goroutine to generat>
Oct 09 04:36:36 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:36:36.383662235Z" level=info msg="Signalling other goroutines waiting for this goroutine to generat>
Oct 09 04:36:36 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:36:36.564797016Z" level=info msg="Signalling other goroutines waiting for this goroutine to generat>
Oct 09 04:36:36 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:36:36.575276320Z" level=info msg="Signalling other goroutines waiting for this goroutine to generat>
Oct 09 04:36:36 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:36:36.961927671Z" level=info msg="Signalling other goroutines waiting for this goroutine to generat>
Oct 09 04:36:37 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:36:37.361856775Z" level=info msg="Signalling other goroutines waiting for this goroutine to generat>
Oct 09 04:36:43 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:36:43.511506677Z" level=info msg="Checking event signatures for 11326 events of room state" context>
Oct 09 04:36:46 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:36:46.099267296Z" level=info msg="Joined federated room with 2027 hosts" room="!qdAzZzmQKYzCeRzqOH:>
Oct 09 04:36:47 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:36:47.843926995Z" level=info msg="Submitting \"m.room.member\" event to roomserver with state snaps>
Oct 09 04:36:54 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:36:54.660875017Z" level=info msg="Starting queue due to pending events or forceWakeup"
Oct 09 04:37:17 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:37:17.491675640Z" level=info msg="User joined room successfully" room_id="#remarkable:matrix.org" s>
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: time="2024-10-09T04:37:22.328104884Z" level=panic msg="roomserver output log: write new event failure" add="[$154762599>
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: 64316CJbma:matrix.org $16313114664840vNOUC:chaosfield.at $1608195391638181sefah:matrix.org $159779810631628xyYTU:t2bot.>
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: 7vnrFv:libera.chat $165056716799189YycIB:t2bot.io $166056061395940ZRedR:matrix.org $1650679185142874aISLS:t2bot.io $165>
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: 5198698904TyHeU:matrix.org $171975454892320cZhuR:t2bot.io $171977613993244LuuvF:t2bot.io $172550123213729QAbuQ:t2bot.io>
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: panic: (*logrus.Entry) 0xc00ff64690
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: goroutine 392 [running]:
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/sirupsen/logrus.(*Entry).log(0xc00ff64620, 0x0, {0xc004e25bc0, 0x2e})
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/sirupsen/logrus.(*Entry).Log(0xc00ff64620, 0x0, {0xc00fe52288?, 0x13dbc1c?, 0x0?})
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/sirupsen/logrus.(*Entry).Panic(...)
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:342
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/MFAshby/stdemuxerhook.(*StdDemuxerHook).Fire(0x0?, 0xc00ff64540)
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/go/pkg/mod/github.com/!m!f!ashby/stdemuxerhook@v1.0.0/stdemuxerhook.go:58 +0x198
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/sirupsen/logrus.LevelHooks.Fire(0xc00fe523c8?, 0xfe52398?, 0x4?)
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/hooks.go:28 +0x70
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/sirupsen/logrus.(*Entry).fireHooks(0xc00ff64540)
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:280 +0x1fa
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/sirupsen/logrus.(*Entry).log(0xc00ff644d0, 0x0, {0xc004e25b90, 0x2e})
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:242 +0x399
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/sirupsen/logrus.(*Entry).Log(0xc00ff644d0, 0x0, {0xc00fe52678?, 0x0?, 0x0?})
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/sirupsen/logrus.(*Entry).Logf(0xc00ff644d0, 0x0, {0x18f65bd?, 0x3?}, {0x0?, 0x0?, 0xc009df62f0?})
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0x7c
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/sirupsen/logrus.(*Entry).Panicf(...)
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:387
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/matrix-org/dendrite/syncapi/consumers.(*OutputRoomEventConsumer).onNewRoomEvent(0xc000139550, {0x1b7fc60, 0x>
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/syncapi/consumers/roomserver.go:290 +0x1038
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/matrix-org/dendrite/syncapi/consumers.(*OutputRoomEventConsumer).onMessage(0xc000139550, {0xc007b1e320?, 0x1>
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/syncapi/consumers/roomserver.go:125 +0x618
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: github.com/matrix-org/dendrite/setup/jetstream.JetStreamConsumer.func2()
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/setup/jetstream/helpers.go:100 +0x454
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]: created by github.com/matrix-org/dendrite/setup/jetstream.JetStreamConsumer in goroutine 1
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 dendrite[129328]:         /opt/dendrite/setup/jetstream/helpers.go:44 +0x2f2
Oct 09 04:37:22 debian-1cpu-1gb-de-fra1 systemd[1]: dendrite.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

This seems to have fixed the crash: https://github.com/matrix-org/dendrite/issues/3148#issuecomment-1628601322
