### ISSUE TITLE
Error: dial tcp: lookup hostname on 127.0.0.11:53: server misbehaving

### ISSUE THREAD

**Issue by nickali** [matrix-org/dendrite#2889]
### Background information

- **Dendrite version or git SHA**: Dendrite version 0.10.7
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **Docker Versions?**: Docker version 20.10.21, build baeda1f
- **`go version`**: N/A
- **Client used (if applicable)**: N/A
- **Environment:** Fresh ARM VPS running Ubuntu 22.04.1

### Description

- **What** is the problem: Dendrite docker instance crashes
- **When** did this first appear: Immediately

### Steps to reproduce

I'm using the default configuration files. I haven't changed anything in the dendrite.yaml file.

I'm firing up Docker with:
```
docker compose -f docker-compose.monolith.yml up -d
```

The errors I see in the logs for the monolith instance:

```
goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0x3174040, 0x0, {0x33e65a0, 0x2c})
	github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4dc
github.com/sirupsen/logrus.(*Entry).Log(0x3174040, 0x0, {0x34c3704, 0x1, 0x1})
	github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x78
github.com/sirupsen/logrus.(*Entry).Panic(...)
	github.com/sirupsen/logrus@v1.9.0/entry.go:342
github.com/MFAshby/stdemuxerhook.(*StdDemuxerHook).Fire(0x33f8a70, 0x315bfc0)
	github.com/MFAshby/stdemuxerhook@v1.0.0/stdemuxerhook.go:58 +0x1b4
github.com/sirupsen/logrus.LevelHooks.Fire(0x34c3794, 0x0, 0x315bfc0)
	github.com/sirupsen/logrus@v1.9.0/hooks.go:28 +0x84
github.com/sirupsen/logrus.(*Entry).fireHooks(0x315bfc0)
	github.com/sirupsen/logrus@v1.9.0/entry.go:280 +0x198
github.com/sirupsen/logrus.(*Entry).log(0x315bf80, 0x0, {0x33e6570, 0x2c})
	github.com/sirupsen/logrus@v1.9.0/entry.go:242 +0x3dc
github.com/sirupsen/logrus.(*Entry).Log(0x315bf80, 0x0, {0x34c3a54, 0x1, 0x1})
	github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x78
github.com/sirupsen/logrus.(*Entry).Panic(...)
	github.com/sirupsen/logrus@v1.9.0/entry.go:342
github.com/matrix-org/dendrite/setup/base.NewBaseDendrite(0x3149200, {0x1430540, 0x8}, {0x34c3e88, 0x0, 0x0})
	github.com/matrix-org/dendrite/setup/base/base.go:223 +0xa80
main.main()
	github.com/matrix-org/dendrite/cmd/dendrite-monolith-server/main.go:69 +0x34c
time="2022-11-23T09:30:02.192048883Z" level=info msg="Dendrite version 0.10.7"
time="2022-11-23T09:30:02.196645008Z" level=panic msg="Failed to set up global database connections" error="failed to find maximum connections: dial tcp: lookup hostname on 127.0.0.11:53: server misbehaving"
panic: (*logrus.Entry) 0x2c703c0
```

Port 53, is it trying to do a DNS lookup?

<details><summary>Postgres Logs</summary>
<p>

#### We can hide anything, even code!

```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2022-11-23 09:41:47.424 UTC [49] LOG:  starting PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-11-23 09:41:47.426 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-11-23 09:41:47.433 UTC [50] LOG:  database system was shut down at 2022-11-23 09:41:47 UTC
2022-11-23 09:41:47.438 UTC [49] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/20-create_db.sh

waiting for server to shut down....2022-11-23 09:41:48.392 UTC [49] LOG:  received fast shutdown request
2022-11-23 09:41:48.394 UTC [49] LOG:  aborting any active transactions
2022-11-23 09:41:48.396 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
2022-11-23 09:41:48.398 UTC [51] LOG:  shutting down
2022-11-23 09:41:48.418 UTC [49] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2022-11-23 09:41:48.515 UTC [1] LOG:  starting PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-11-23 09:41:48.531 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-11-23 09:41:48.531 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2022-11-23 09:41:48.536 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-11-23 09:41:48.543 UTC [80] LOG:  database system was shut down at 2022-11-23 09:41:48 UTC
2022-11-23 09:41:48.549 UTC [1] LOG:  database system is ready to accept connections
```

</p>
</details>

**Comment by kegsay** [comment]
It sounds like your database connection string is incorrect. What is it set to (password/etc removed)?

**Comment by matslarson** [comment]
> I'm using the default configuration files. I haven't changed anything in the dendrite.yaml file.

if you mean you haven’t changed https://github.com/matrix-org/dendrite/blob/31f56ac3f43b692a56718fd1acfcb5a46e485c57/dendrite-sample.monolith.yaml#L44 you’ll need to either change that string to point to your Postgres server or run Postgres with those exact parameters. The example files are intended as examples, not to be run as-is.

**Comment by nickali** [comment]
I've made some changes but I'm still getting an error:

```logs
time="2022-11-23T20:53:17.568334846Z" level=panic msg="Failed to set up global database connections" error="failed to find maximum connections: dial tcp 10.5.0.5:5432: connect: connection refused"
```

dendrite.yaml and docker-compose.monolith.yaml are attached.

In docker-compose.monolith.yaml, I added a separate network and set the Postgres username and password:

```yaml
    environment:
      POSTGRES_PASSWORD: dendrite
      POSTGRES_USER: dendrite
...
    networks:
      dendrite-network:
        ipv4_address: 10.5.0.5
```

And for monolith section:

```yaml
    networks:
      dendrite-network:
        ipv4_address: 10.5.0.10
    restart: unless-stopped
```

And for the subnet::

```yaml
networks:
  dendrite-network:
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
    attachable: true
```

The connection string from dendrite.yaml:

```yaml
  database:
    connection_string: postgresql://dendrite:dendrite@10.5.0.5/dendrite?sslmode=disable
    max_open_conns: 90
    max_idle_conns: 5
    conn_max_lifetime: -1
```

I shell into the monolith and add the postgres-client package. Then I try:

```shell
psql postgresql://dendrite:dendrite@10.5.0.5/dendrite?sslmode=disable
```

It connects and goes into the right database. Here is a screenshot of the tables:
![Screen Shot 2022-11-23 at 3 49 39 PM](https://user-images.githubusercontent.com/1514992/203644826-fca9a7c1-ae55-47fe-89b5-328d524ebbd8.png)




[docker-compose.monolith.yml.txt](https://github.com/matrix-org/dendrite/files/10079144/docker-compose.monolith.yml.txt)
[dendrite.yaml.txt](https://github.com/matrix-org/dendrite/files/10079145/dendrite.yaml.txt)

**Comment by nickali** [comment]
After some frustration, I started from a new VPS and it all works fine. 🤷🏼‍♂️
