### ISSUE TITLE
Crash in logging when inviting a user to a room from Riot

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#320]
Inviting a user that doesn't exist to a room sometimes results in the following crash:

```
INFO[2017-11-05T19:28:30.841309575Z] Incoming request                              req.id=wh6BQnuWvRsy req.method=OPTIONS req.path="/_matrix/client/r0/rooms/!BW8Y552vsnLTa6Vv:localhost/typing/@testguest:localhost"
INFO[2017-11-05T19:28:30.845994460Z] Incoming request                              req.id=PJKUTHSnFm9W req.method=PUT req.path="/_matrix/client/r0/rooms/!BW8Y552vsnLTa6Vv:localhost/typing/@testguest:localhost"
INFO[2017-11-05T19:28:30.846047385Z] Responding (2 bytes)                          code=200 req.id=PJKUTHSnFm9W req.method=PUT req.path="/_matrix/client/r0/rooms/!BW8Y552vsnLTa6Vv:localhost/typing/@testguest:localhost"
INFO[2017-11-05T19:28:33.897528804Z] Responding (116 bytes)                        code=200 req.id=GEP50eCv4viI req.method=GET req.path=/_matrix/client/r0/sync
INFO[2017-11-05T19:28:33.914482028Z] Incoming request                              req.id=qoYeuD0qV1C6 req.method=GET req.path=/_matrix/client/r0/sync
INFO[2017-11-05T19:28:33.914726260Z] Incoming /sync request                        req.id=qoYeuD0qV1C6 req.method=GET req.path=/_matrix/client/r0/sync since=10 timeout=30s userID="@testguest:localhost"
INFO[2017-11-05T19:28:33.914753230Z] Waiting for event                             req.id=qoYeuD0qV1C6 req.method=GET req.path=/_matrix/client/r0/sync user_id="@testguest:localhost"
INFO[2017-11-05T19:28:36.737038709Z] Incoming request                              req.id=5OqxBHv2R7YO req.method=POST req.path="/_matrix/client/r0/rooms/!BW8Y552vsnLTa6Vv:localhost/invite"
INFO[2017-11-05T19:28:36.757531202Z] received event from roomserver                event_id="$PTWjoBf4KYU68c9x:localhost" room_id="!BW8Y552vsnLTa6Vv:localhost" send_as_server=localhost
INFO[2017-11-05T19:28:36.757987543Z] received event from roomserver                event_id="$PTWjoBf4KYU68c9x:localhost" room_id="!BW8Y552vsnLTa6Vv:localhost"
PANI[2017-11-05T19:28:36.759502246Z] roomserver output log: write event failure    add="[$PTWjoBf4KYU68c9x:localhost]" del="[]" error="mismatched last sent event ID: had \"$4qKSOZcVDvWy3rXp:localhost\" in database got \"$dQ5vkH0t83cdIU7i:localhost\" from room server" event="{\"auth_events\":[[\"$pTV2xe84YsgStwo9:localhost\",{\"sha256\":\"Qha/9MQ5gqg7C4ILfdEgIyTLXTZnUQqERDpYg+WxUyM\"}],[\"$CZq6zr9eaECaTS4w:localhost\",{\"sha256\":\"MC1bF8jttJo+FfA2S6Ir8moogkH6NXrdyeQOWUGkMw8\"}],[\"$tKPyaq36smduCo3v:localhost\",{\"sha256\":\"Y5MPjekqVew4u0ve5qI5pQ66MDrPx3qnfytDZb2z69U\"}]],\"content\":{\"membership\":\"invite\"},\"depth\":12,\"event_id\":\"$PTWjoBf4KYU68c9x:localhost\",\"hashes\":{\"sha256\":\"1Wiv5GCakClHhgh9G5Bf+Llhd4xGOorAVvxycS6pdv4\"},\"origin\":\"localhost\",\"origin_server_ts\":1509910116739,\"prev_events\":[[\"$dQ5vkH0t83cdIU7i:localhost\",{\"sha256\":\"CWbxrhN85GteatcWyma9NJ1L9IfoQOtHVR8uqLpOA0o\"}]],\"prev_state\":[],\"room_id\":\"!BW8Y552vsnLTa6Vv:localhost\",\"sender\":\"@testguest:localhost\",\"signatures\":{\"localhost\":{\"ed25519:KRVR\":\"yAvHBe5qXP8QDgHR3WU5RU1AdgvpEZaTeoRTEFKhS0Su0LEK4yQuQBkhN6phr2DdJ73+UBMfaX80iqKi51tWDg\"}},\"state_key\":\"@andrewm:matrix.org\",\"type\":\"m.room.member\"}"
panic: (*logrus.Entry) (0xab1760,0xc42072cdc0)

goroutine 46 [running]:
github.com/sirupsen/logrus.Entry.log(0xc42006e230, 0xc420ca61b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/user/dendrite/vendor/src/github.com/sirupsen/logrus/entry.go:128 +0x615
github.com/sirupsen/logrus.(*Entry).Panic(0xc42072cd70, 0xc420de59b8, 0x1, 0x1)
	/home/user/dendrite/vendor/src/github.com/sirupsen/logrus/entry.go:173 +0xaa
github.com/sirupsen/logrus.(*Entry).Panicf(0xc42072cd70, 0xadb513, 0x2a, 0x0, 0x0, 0x0)
	/home/user/dendrite/vendor/src/github.com/sirupsen/logrus/entry.go:221 +0xf7
github.com/matrix-org/dendrite/federationsender/consumers.(*OutputRoomEventConsumer).onMessage(0xc4201c4780, 0xc42012a9a0, 0xc420208f01, 0x101)
	/home/user/dendrite/src/github.com/matrix-org/dendrite/federationsender/consumers/roomserver.go:102 +0x88d
github.com/matrix-org/dendrite/federationsender/consumers.(*OutputRoomEventConsumer).(github.com/matrix-org/dendrite/federationsender/consumers.onMessage)-fm(0xc42012a9a0, 0xc420208fa0, 0xc4201d3e01)
	/home/user/dendrite/src/github.com/matrix-org/dendrite/federationsender/consumers/roomserver.go:60 +0x34
github.com/matrix-org/dendrite/common.(*ContinualConsumer).consumePartition(0xc4201a6c40, 0xdf0800, 0xc4201d3e80)
	/home/user/dendrite/src/github.com/matrix-org/dendrite/common/consumers.go:112 +0xdf
created by github.com/matrix-org/dendrite/common.(*ContinualConsumer).Start
	/home/user/dendrite/src/github.com/matrix-org/dendrite/common/consumers.go:102 +0x479
```

Panic is printed [here](https://github.com/matrix-org/dendrite/blob/b7cfc2e057439334e3ddfa69cebff653f3114d00/src/github.com/matrix-org/dendrite/federationsender/consumers/roomserver.go#L102).

**Comment by MTRNord** [comment]
Same crash `mismatched last sent event ID:` happens on a broken federation room after reseting the DB. But the federation is I think because of missing backpagination in the federation.

**Comment by MTRNord** [comment]
Same crash `mismatched last sent event ID:` happens on a broken federation room after reseting the DB. But the federation is I think because of missing backpagination in the federation.

**Comment by Kegsay** [comment]
Closing this issue as it is reporting a bug which is over 1 year old and would be difficult to correlate with today's code.
