### ISSUE TITLE
Panic in d.Receipts.SelectMaxReceiptID when starting Dentrite

### ISSUE THREAD

**Issue by Undef-a** [matrix-org/dendrite#3241]
### Background information
- **Dendrite version or git SHA**: 0.13.3+b341a66
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.20 (not entirely sure here)

### Description

- **What** is the problem: Dendrite crashes with a panic on startup. This happens every startup.
- **When** did this first appear: About a week ago, I upgraded to 0.13.3 long before the bug started.

### Steps to reproduce

Unknown, this is likely due to some data in my Dendrite DB rather than something user-triggerable.

### Logs
```
panic: d.Receipts.SelectMaxReceiptID: pq: could not read block 9288 in file "base/16385/16983": read only 0 of 8192 bytes
goroutine 1 [running]:
github.com/matrix-org/dendrite/syncapi/streams.(*ReceiptStreamProvider).Setup(0xc0053d5bf0, {0x1b18b18, 0x26e9840}, {0x1b332a0, 0xc00306bb40})
        /home/user/src/dendrite/syncapi/streams/stream_receipt.go:28 +0xc9
github.com/matrix-org/dendrite/syncapi/streams.NewSyncStreamProviders({0x1b2ef10?, 0xc0025b5200}, {0x7f82eec3bdd8?, 0xc0000e2990}, {0x7f82eec3be38?, 0xc002d0c2c0}, 0xc0053d5ad0, {0x1b15e80?, 0xc0001ae340}, 0xc002ce1900)
        /home/user/src/dendrite/syncapi/streams/streams.go:81 +0x791
github.com/matrix-org/dendrite/syncapi.AddPublicRoutes(0xc00035c3c0, {0xc00049e480, 0xc00049e540, 0xc00049e600, 0xc00049e6c0, 0xc00049e780, 0xc00049e840, 0xc00049e900, 0xc00049e9c0}, 0xc0001ec700, ...)
        /home/user/src/dendrite/syncapi/syncapi.go:64 +0x21e
github.com/matrix-org/dendrite/setup.(*Monolith).AddAllPublicRoutes(0xc000315ce0, 0xc002d0c2c0?, 0x4183e8?, {0xc00049e480, 0xc00049e540, 0xc00049e600, 0xc00049e6c0, 0xc00049e780, 0xc00049e840, 0xc00049e900, ...}, ...)
        /home/user/src/dendrite/setup/monolith.go:82 +0x5ab
main.main()
        /home/user/src/dendrite/cmd/dendrite/main.go:184 +0xf1b
```

**Comment by S7evinK** [comment]
This sounds more like the database is in a bad state. Nothing Dendrite can handle.

**Comment by Undef-a** [comment]
I guess this is what backups are for then. All working again after a little backfill. Thanks.
