### ISSUE TITLE
p2p: crash when receiving request

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#933]
Just before we get an HTTP request from JS-land. Looks to be a Go bug.

```
Received request:

runtime: unexpected return pc for runtime.handleEvent called from 0x43e0000000000000
wasm_exec.js?3f15:44 stack: frame={sp:0x2c5d348, fp:0x2c5d378} stack=[0x2c5a000,0x2c62000)
wasm_exec.js?3f15:44 0000000002c5d248:  00000000000058f7  0000000002d0a000 
wasm_exec.js?3f15:44 0000000002c5d258:  00000000001e2200  000000000101f1e0 
wasm_exec.js?3f15:44 0000000002c5d268:  0000000050e60002 <main.(*JSServer).OnRequestFromJS-fm+2>  000000000100cd50 
wasm_exec.js?3f15:44 0000000002c5d278:  7ff800000000026a  000000000101f1c0 
wasm_exec.js?3f15:44 0000000002c5d288:  0000000000000001  0000000000000001 
wasm_exec.js?3f15:44 0000000002c5d298:  7ff8000100000f03  000000000101f1c0 
wasm_exec.js?3f15:44 0000000002c5d2a8:  0000000018b9001d <syscall/js.handleEvent+29>  7ff800000000026a 
wasm_exec.js?3f15:44 0000000002c5d2b8:  000000000101f1c0  0000000000000001 
wasm_exec.js?3f15:44 0000000002c5d2c8:  0000000000000001  000000000101f101 
wasm_exec.js?3f15:44 0000000002c5d2d8:  15fddc62822ee600  0000000000000000 
wasm_exec.js?3f15:44 0000000002c5d2e8:  0100000000000000  0000000000000017 
wasm_exec.js?3f15:44 0000000002c5d2f8:  0000000000000000  0000000000000001 
wasm_exec.js?3f15:44 0000000002c5d308:  7ff800000005c3d4  7ff800000000026a 
wasm_exec.js?3f15:44 0000000002c5d318:  7ff800000005c3d3  0000000001295400 
wasm_exec.js?3f15:44 0000000002c5d328:  000000000101f1c0  0000000000000000 
wasm_exec.js?3f15:44 0000000002c5d338:  ffffffffffffffff  0000000010a90007 <runtime.handleEvent+7> 
wasm_exec.js?3f15:44 0000000002c5d348: <0000000002c5d368  0000000000000000 
wasm_exec.js?3f15:44 0000000002c5d358:  43e0000000000000  0000000000000001 
wasm_exec.js?3f15:44 0000000002c5d368:  00000000011d1980 !43e0000000000000 
wasm_exec.js?3f15:44 0000000002c5d378: >0000000000202295  0000000000000009 
wasm_exec.js?3f15:44 0000000002c5d388:  43e0000000000000  0000000000000001 
wasm_exec.js?3f15:44 0000000002c5d398:  0000000000000001  7ff800000005b842 
wasm_exec.js?3f15:44 0000000002c5d3a8:  0000000000000002  0000000000000000 
wasm_exec.js?3f15:44 0000000002c5d3b8:  000000001f070006 <context.(*valueCtx).Done+6>  7ff800000005b842 
wasm_exec.js?3f15:44 0000000002c5d3c8:  0000000000000000  0000000002c5d388 
wasm_exec.js?3f15:44 0000000002c5d3d8:  00000000001d2840  00000000011e60f8 
wasm_exec.js?3f15:44 0000000002c5d3e8:  0000000050c20029 <github.com/matrix-org/go-sqlite3-js.(*SqliteJsRows).Next+41>  0000000002cf93a0 
wasm_exec.js?3f15:44 0000000002c5d3f8:  000000000259e140  0000000000000005 
wasm_exec.js?3f15:44 0000000002c5d408:  0000000000000005  0000000000000000 
wasm_exec.js?3f15:44 0000000002c5d418:  0000000000000000  0000000010b00051 <runtime.mallocgc+81> 
wasm_exec.js?3f15:44 0000000002c5d428:  000000000287f508  0000000000000008 
wasm_exec.js?3f15:44 0000000002c5d438:  0000000002c5d3f0  0000000050c20009 <github.com/matrix-org/go-sqlite3-js.(*SqliteJsRows).Next+9> 
wasm_exec.js?3f15:44 0000000002c5d448:  0000000000363c40  0000000000000000 
wasm_exec.js?3f15:44 0000000002c5d458:  0000000002c5d510  0000000002cf9390 
wasm_exec.js?3f15:44 0000000002c5d468:  0000000002c74db0  000000000287f508 
wasm_exec.js?3f15:44 fatal error: unknown caller pc

wasm_exec.js?3f15:44 
wasm_exec.js?3f15:44 goroutine 11871 [waiting (scan), 13 minutes]:
wasm_exec.js?3f15:44 syscall/js.Value.New(0x7ff800030000027d, 0x2c5d258, 0x1, 0x1, 0xf800000005c3d2)
wasm_exec.js?3f15:44 	/usr/local/go/src/syscall/js/js.go:350 +0x3
wasm_exec.js?3f15:44 main.(*JSServer).OnRequestFromJS(0x100cd50, 0x7ff800000000026a, 0x101f1c0, 0x1, 0x1, 0x7ff8000100000f03, 0x101f1c0)
wasm_exec.js?3f15:44 	/Users/kegan/github/dendrite/cmd/dendritejs/jsServer.go:47 +0xa
wasm_exec.js?3f15:44 syscall/js.handleEvent()
wasm_exec.js?3f15:44 	/usr/local/go/src/syscall/js/func.go:90 +0x1d
wasm_exec.js?3f15:44 fatal error: unexpected signal during runtime execution
```

**Comment by Kegsay** [comment]
This was an int64 bug - fixed in https://github.com/matrix-org/dendrite/commit/bfb954519bdf172451d999ac4c654b3d15eff124
